/* =====================================================================
   "Pulse of Diriyah and Its Nights" — English judging deck (WRO 2026)
   Same scenes as ../diriyah-judges (widgetsD_en.js is generated by make-en.py)
   ===================================================================== */
(function (root) {
root.DECK = {
  lang: 'en',
  title: 'Pulse of Diriyah and Its Nights',
  subtitle: 'An interactive sound & light show… that sees the visitor and decides by itself',
  tag: 'WRO 2026 · Future Innovators · Judging presentation',
  author: 'Talent & AI Unit · Al-Arqam Schools',
  sectionLabel: 'Section',
  parts: ['01-idea', '02-parts', '03-build', '04-labs', '04b-new', '04c-caravan', '05-end'],
  modules: [],
};
if (typeof module !== 'undefined' && module.exports) module.exports = root.DECK;
})(typeof window !== 'undefined' ? window : globalThis);
