/* =====================================================================
   English build — generated by make-en.py from widgetsD.js
   الأنواع: dyhero · dysystem · dycurtain · dyir · dyrgb · dynow · dydecision · dyevolve
   كل مشهد متحرك يُرسم بدالة draw(t) من الزمن وحده، فيمكن تصويره إطارًا إطارًا
   (window.DY_ANIM) ليصير صورة متحركة GIF داخل البوربوينت.
   البادئة dy لكل الأصناف حتى لا تتصادم مع أنماط الدورات الأخرى.
   ===================================================================== */
(function () {
const L = x => '⁦' + x + '⁩';   // عزل نص لاتيني داخل جملة عربية
const AR = n => String(n);

/* ---------- حقائق المشروع من الكود الفعلي (smart-heritage-house) ---------- */
const ST = [
  { n: 'Salwa Palace', s: 'Seat of rule of the First Saudi State', ir: 18, led: 25, ch: [2, 1, 0], trk: 2, x: 1470 },
  { n: 'Imam Mohammed bin Saud Mosque', s: 'Prayer and circles of learning', ir: 19, led: 26, ch: [5, 4, 3], trk: 3, x: 1045 },
  { n: 'Wadi Hanifa', s: 'The lifeline: water and palms', ir: 23, led: 27, ch: [8, 7, 6], trk: 4, x: 620 },
];
const BTN = [
  { n: 'Welcome', c: '#f2c230', pin: 33, trk: 1, r: 'Welcome to the Nights of Diriyah' },
  { n: 'Awareness', c: '#2e9e6b', pin: 26, trk: 5, r: 'People learn the value of Diriyah' },
  { n: 'Participation', c: '#2f6fd0', pin: 27, trk: 6, r: 'Every visitor protects it' },
  { n: 'Innovation', c: '#d64545', pin: 25, trk: 7, r: 'Technology guards heritage' },
];
const TRACKS = ['Welcome (after the door)', 'Station: Salwa Palace', 'Station: the Mosque', 'Station: Wadi Hanifa', 'Result: Awareness', 'Result: Participation', 'Result: Innovation', 'Closing', 'Extra: Salwa Palace', 'Extra: the Mosque', 'Extra: Wadi Hanifa', 'Old door sound (opening)'];
const HOLD = 12;
const SND = n => `audio/${String(n).padStart(4, '0')}.mp3`;
let dyAudio = null;
function playSnd(n) { try { if (dyAudio) dyAudio.pause(); dyAudio = new Audio(SND(n)); dyAudio.play().catch(() => {}); } catch (e) {} }
function stopSnd() { try { if (dyAudio) dyAudio.pause(); } catch (e) {} dyAudio = null; }                 // HOLD_DURATION_MS = 12000
const HUE_MS = 15;               // rainbowHue + 1 كل 15 مللي ثانية

/* ---------- أدوات رسم عامة ---------- */
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const lerp = (a, b, k) => a + (b - a) * clamp(k, 0, 1);
const ease = k => { k = clamp(k, 0, 1); return k * k * (3 - 2 * k); };
// نفس حساب setRGBHue في الكود (أعداد صحيحة)
function hueRGB(h) {
  h = ((Math.floor(h) % 360) + 360) % 360;
  const region = Math.floor(h / 60), rem = Math.floor((h % 60) * 255 / 60), F = 4095;
  const rising = rem * Math.floor(F / 255), falling = F - rising;
  return [[F, rising, 0], [falling, F, 0], [0, F, rising], [0, falling, F], [rising, 0, F], [F, 0, falling]][region].concat(region);
}
const css = ([r, g, b]) => `rgb(${Math.round(r / 16)},${Math.round(g / 16)},${Math.round(b / 16)})`;

const DEFS = `<defs>
  <linearGradient id="dyCone" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffe29a" stop-opacity=".85"/><stop offset="1" stop-color="#ffcf6a" stop-opacity="0"/></linearGradient>
  <radialGradient id="dyGlow"><stop offset="0" stop-color="#fff" stop-opacity=".9"/><stop offset=".4" stop-color="#fff" stop-opacity=".35"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient>
  <linearGradient id="dyMud" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#d9a868"/><stop offset="1" stop-color="#a8743f"/></linearGradient>
  <linearGradient id="dyMud2" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#b98348"/><stop offset="1" stop-color="#8f5f30"/></linearGradient>
  <linearGradient id="dyCurt" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#3a0d16"/><stop offset=".5" stop-color="#6b1a26"/><stop offset="1" stop-color="#3a0d16"/></linearGradient>
  <linearGradient id="dySky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#070a1c"/><stop offset="1" stop-color="#18203f"/></linearGradient>
  <pattern id="dyFold" width="46" height="10" patternUnits="userSpaceOnUse"><rect width="46" height="10" fill="url(#dyCurt)"/></pattern>
</defs>`;
const stars = (n, w, h) => Array.from({ length: n }, (_, i) => `<circle cx="${(i * 397 + 53) % w}" cy="${(i * 131) % h + 8}" r="${i % 4 ? 1.3 : 2.2}" fill="#fff" opacity="${.3 + (i % 5) / 10}"/>`).join('');

/* قصر سلوى (حي الطريف): كتلة طينية بشرفات مسننة ونوافذ مثلثة */
function palace(cx, by, k = 1) {
  const w = 230 * k, h = 165 * k, x = cx - w / 2, y = by - h;
  const teeth = n => Array.from({ length: n }, (_, i) => `<path d="M${x + i * w / n + 4} ${y} l${w / n / 2 - 4} -${16 * k} l${w / n / 2 - 4} ${16 * k}z" fill="#c99556"/>`).join('');
  const tri = (tx, ty) => `<path d="M${tx} ${ty} l${11 * k} -${16 * k} l${11 * k} ${16 * k}z" fill="#3b2412"/>`;
  return `<g><rect x="${x - 60 * k}" y="${by - 105 * k}" width="${70 * k}" height="${105 * k}" fill="url(#dyMud2)"/>
    <rect x="${x + w - 10 * k}" y="${by - 215 * k}" width="${62 * k}" height="${215 * k}" fill="url(#dyMud2)"/>
    ${Array.from({ length: 3 }, (_, i) => `<path d="M${x + w - 6 * k + i * 19 * k} ${by - 215 * k} l${8 * k} -${13 * k} l${8 * k} ${13 * k}z" fill="#b98348"/>`).join('')}
    <rect x="${x}" y="${y}" width="${w}" height="${h}" fill="url(#dyMud)"/>${teeth(9)}
    ${[0, 1, 2].map(i => tri(x + 40 * k + i * 62 * k, y + 50 * k)).join('')}
    ${[0, 1, 2, 3].map(i => `<rect x="${x + 30 * k + i * 50 * k}" y="${y + 80 * k}" width="${10 * k}" height="${16 * k}" fill="#3b2412"/>`).join('')}
    <path d="M${cx - 22 * k} ${by} v-${50 * k} q${22 * k} -${22 * k} ${44 * k} 0 v${50 * k}z" fill="#4a2c14"/>
    <rect x="${x + w + 8 * k}" y="${by - 170 * k}" width="${9 * k}" height="${14 * k}" fill="#3b2412"/><rect x="${x + w + 28 * k}" y="${by - 120 * k}" width="${9 * k}" height="${14 * k}" fill="#3b2412"/></g>`;
}
/* مسجد الإمام محمد بن سعود: مصلى طيني واسع بشرفات، ومئذنة نجدية مستدقة، وجسر يصله بقصر سلوى */
function mosque(cx, by, k = 1) {
  const x = cx - 170, w = 300, h = 120;
  const mx = cx + 70, mw0 = 66, mw1 = 44, mh = 250;   // المئذنة تضيق كلما ارتفعت
  return `<g><rect x="${x}" y="${by - h}" width="${w}" height="${h}" fill="url(#dyMud)"/>
    ${Array.from({ length: 12 }, (_, i) => `<path d="M${x + i * 25} ${by - h} l12.5 -15 l12.5 15z" fill="#c99556"/>`).join('')}
    ${Array.from({ length: 6 }, (_, i) => `<rect x="${x + 22 + i * 44}" y="${by - h + 36}" width="12" height="22" fill="#3b2412"/>`).join('')}
    ${Array.from({ length: 4 }, (_, i) => `<path d="M${x + 40 + i * 64} ${by} v-34 q14 -16 28 0 v34z" fill="#4a2c14"/>`).join('')}
    <path d="M${mx - mw0 / 2} ${by} L${mx - mw1 / 2} ${by - mh} H${mx + mw1 / 2} L${mx + mw0 / 2} ${by}z" fill="url(#dyMud2)"/>
    ${[0, 1, 2, 3].map(i => `<rect x="${mx - 5}" y="${by - mh + 30 + i * 52}" width="10" height="18" fill="#3b2412"/>`).join('')}
    <rect x="${mx - mw1 / 2 - 6}" y="${by - mh - 8}" width="${mw1 + 12}" height="10" fill="#c99556"/>
    ${[0, 1, 2].map(i => `<path d="M${mx - mw1 / 2 - 6 + i * 19} ${by - mh - 8} l9.5 -14 l9.5 14z" fill="#c99556"/>`).join('')}
    <path d="M${x + w} ${by - 78} h${70} v18 h-${70}z" fill="#a8743f"/><path d="M${x + w + 12} ${by - 60} v60 M${x + w + 58} ${by - 60} v60" stroke="#8f5f30" stroke-width="10"/>
    ${person(cx - 120, by, '#e8dcc0', 0, .55)}</g>`;
}
/* وادي حنيفة: مجرى ماء بين ضفتين، ونخيل ومزارع، وبيوت طينية على الضفة البعيدة */
function wadi(cx, by, k = 1) {
  const palm = (x, h) => `<path d="M${x} ${by - 20} q-6 -${h / 2} 4 -${h}" stroke="#6b4a2a" stroke-width="9" fill="none"/>
    ${[-70, -35, 0, 35, 70, 110, -110].map(a => `<path d="M${x + 4} ${by - 20 - h} q${Math.sin(a * Math.PI / 180) * 40} -30 ${Math.sin(a * Math.PI / 180) * 75} ${Math.cos(a * Math.PI / 180) * 18 + 12}" stroke="#3f7a3a" stroke-width="7" fill="none" stroke-linecap="round"/>`).join('')}`;
  return `<g>${[0, 1, 2].map(i => `<rect x="${cx - 160 + i * 52}" y="${by - 150 - i * 6}" width="44" height="${40 + i * 6}" fill="#9c6a3a" opacity=".75"/>`).join('')}
    <path d="M${cx - 200} ${by - 60} Q ${cx} ${by - 110} ${cx + 200} ${by - 60} V ${by} H ${cx - 200}z" fill="#8a5a2c"/>
    <path d="M${cx - 200} ${by - 26} Q ${cx - 60} ${by - 52} ${cx + 30} ${by - 30} T ${cx + 200} ${by - 34} V ${by - 10} Q ${cx + 40} ${by - 2} ${cx - 200} ${by - 8}z" fill="#3c8fc4"/>
    <path d="M${cx - 150} ${by - 22} q30 -6 60 0 M${cx - 20} ${by - 24} q30 -6 60 0 M${cx + 100} ${by - 26} q30 -6 60 0" stroke="#bfe6ff" stroke-width="3" fill="none" opacity=".8"/>
    ${palm(cx - 150, 120)}${palm(cx - 70, 150)}${palm(cx + 90, 135)}${palm(cx + 165, 110)}
    <rect x="${cx - 30}" y="${by - 62}" width="70" height="20" fill="#3f7a3a"/><rect x="${cx - 30}" y="${by - 62}" width="70" height="20" fill="none" stroke="#7a5230" stroke-width="3"/></g>`;
}
/* زائر بسيط يمشي (phase يحرك الساقين) */
function person(x, by, col = '#f6e7c9', phase = 0, k = 1) {
  const sw = Math.sin(phase) * 14 * k;
  return `<g transform="translate(${x} ${by})"><line x1="0" y1="${-46 * k}" x2="${sw}" y2="0" stroke="${col}" stroke-width="${9 * k}" stroke-linecap="round"/>
    <line x1="0" y1="${-46 * k}" x2="${-sw}" y2="0" stroke="${col}" stroke-width="${9 * k}" stroke-linecap="round"/>
    <path d="M${-17 * k} ${-46 * k} q0 ${-62 * k} ${17 * k} ${-62 * k} q${17 * k} 0 ${17 * k} ${62 * k}z" fill="${col}"/>
    <circle cy="${-122 * k}" r="${15 * k}" fill="${col}"/></g>`;
}
/* لوحة ESP32 صغيرة */
function esp(x, y, w, h, lbl, on) {
  return `<g transform="translate(${x} ${y})"><rect width="${w}" height="${h}" rx="10" fill="#14324f" stroke="${on ? '#7ee2a8' : '#3a5a7a'}" stroke-width="${on ? 5 : 3}"/>
    <rect x="${w / 2 - 32}" y="16" width="64" height="44" rx="4" fill="#1f2a36" stroke="#9aa8b8" stroke-width="2"/><text x="${w / 2}" y="44" class="dyt" style="font-size:15px;fill:#cfd8e3">ESP32</text>
    ${Array.from({ length: 9 }, (_, i) => `<rect x="${8 + i * (w - 16) / 9}" y="${h - 9}" width="6" height="9" fill="#d9ae4b"/>`).join('')}
    <circle cx="${w - 16}" cy="16" r="6" fill="${on ? '#7ee2a8' : '#34465a'}"/>
    <text x="${w / 2}" y="${h - 22}" class="dyt" style="font-size:17px;fill:#f0cc7a">${lbl}</text></g>`;
}
function speaker(x, y, on, t, k = 1) {
  const w = (i) => on ? (.25 + .75 * ((Math.sin(t * 7 - i) + 1) / 2)) : .12;
  return `<g transform="translate(${x} ${y}) scale(${k})"><rect x="-18" y="-16" width="16" height="32" fill="#c9cfe6"/><path d="M-2 -16 l24 -20 v72 l-24 -20z" fill="#c9cfe6"/>
    ${[0, 1, 2].map(i => `<path d="M${32 + i * 14} -${18 + i * 9} q${12 + i * 5} ${18 + i * 9} 0 ${36 + i * 18}" stroke="#f0cc7a" stroke-width="5" fill="none" opacity="${w(i)}" stroke-linecap="round"/>`).join('')}</g>`;
}
function irMod(x, y, hit, k = 1) {
  return `<g transform="translate(${x} ${y}) scale(${k})"><rect x="-30" y="-14" width="60" height="28" rx="5" fill="#1d5fa8" stroke="#9ec5f2" stroke-width="2"/>
    <circle cx="-12" cy="0" r="7" fill="#dfe6ef"/><circle cx="12" cy="0" r="7" fill="#222"/>
    <circle cx="24" cy="-8" r="3.5" fill="${hit ? '#ff4d4d' : '#4a2020'}"/></g>`;
}
/* الستارة تُرفع لأعلى: frac 0 مغلقة … 1 مرفوعة بالكامل (بكرة أعلى الصندوق يلتف عليها خيط) */
function curtain(x0, x1, y0, y1, frac) {
  const H = y1 - y0, hb = Math.max(26, H * (1 - frac)), yb = y0 + hb, w = x1 - x0, nf = Math.floor(w / 46);
  const folds = Array.from({ length: nf }, (_, i) => { const x = x0 + (i + .5) * w / nf; return `<line x1="${x}" y1="${y0}" x2="${x}" y2="${yb}" stroke="#1d050a" stroke-width="5" opacity=".55"/>`; }).join('');
  const sc = Array.from({ length: nf }, (_, i) => `a${w / nf / 2} 12 0 0 1 ${w / nf} 0`).join(' ');
  const bunch = frac > .05 ? Array.from({ length: 3 }, (_, i) => `<path d="M${x0} ${y0 + 8 + i * 7} q${w / 4} 6 ${w / 2} 0 t${w / 2} 0" stroke="#3a0d16" stroke-width="4" fill="none" opacity="${.4 + frac * .4}"/>`).join('') : '';
  const strings = [0.2, 0.5, 0.8].map(k => `<line x1="${x0 + w * k}" y1="${y0 - 6}" x2="${x0 + w * k}" y2="${yb}" stroke="#d9c79a" stroke-width="2" opacity=".7"/>`).join('');
  return `<rect x="${x0}" y="${y0}" width="${w}" height="${hb}" fill="url(#dyFold)"/>${folds}${bunch}
    <path d="M${x0} ${yb} ${sc} V ${yb - 8} H ${x0}z" fill="#d9ae4b" opacity=".85"/>${strings}
    <rect x="${x0 - 10}" y="${y0 - 18}" width="${w + 20}" height="24" rx="12" fill="#2a1a0c"/><circle cx="${x0 + 6}" cy="${y0 - 6}" r="9" fill="#8a611f"/><circle cx="${x1 - 6}" cy="${y0 - 6}" r="9" fill="#8a611f"/>`;
}

/* ---------- الديوراما الكاملة (المشهد البطل) ---------- */
// الحالة الكاملة للعرض عند الزمن t (دورة ٤٠ ث)، تُحسب من t وحده
const HP = 69, SW = 11.5;            // دورة المشهد، ومدة كل محطة (أطول مقطع محطة ١٠٫٧ ث)
const WIN = [[15.5, 27], [29, 40.5], [42.5, 54]];
function heroState(t) {
  const ph = t % HP, loop = Math.floor(t / HP);
  const cur = ph < .5 ? 0 : ph < 4.5 ? (ph - .5) / 4 : ph < 66 ? 1 : 1 - (ph - 66) / 3;
  let st = -1, since = 0;
  WIN.forEach(([a, b], i) => { if (ph >= a && ph < b) { st = i; since = ph - a; } });
  const path = [[13.5, 1760], [15.5, ST[0].x], [27, ST[0].x], [29, ST[1].x], [40.5, ST[1].x], [42.5, ST[2].x], [54, ST[2].x], [56, 250], [66, 250], [68.5, -80]];
  let vx = null, walking = false;
  if (ph >= 13.5 && ph < 68.5) for (let i = 0; i < path.length - 1; i++) {
    const [ta, xa] = path[i], [tb, xb] = path[i + 1];
    if (ph >= ta && ph < tb) { vx = lerp(xa, xb, ease((ph - ta) / (tb - ta))); walking = xa !== xb; }
  }
  const choice = 1 + loop % 3;
  const press = ph >= 57.5 && ph < 58.2;
  const result = ph >= 57.5 && ph < 66;
  let track = 0;
  if (ph < 4) track = 12;
  else if (ph < 13.5) track = 1;
  else if (st >= 0 && since > .8) track = ST[st].trk;
  else if (result) track = BTN[choice].trk;
  const pkt = st >= 0 && since < .8 ? since / .8 : -1;
  let cap;
  if (ph < 4.5) cap = ['🚪', 'An old door creaks open… and the stepper motor raises the curtain (' + L('0012.mp3') + ')'];
  else if (ph < 13.5) cap = ['🎙️', 'The narrator welcomes visitors (' + L('0001.mp3') + ')… and Diriyah comes alive at night'];
  else if (st >= 0) cap = since < .8 ? ['📡', `The IR sensor at “${ST[st].n}” sees the visitor → sends ${L("'" + ST[st].trk + "'")} wirelessly over ESP-NOW`]
    : ['💡', `${ST[st].n}: spotlight, colors + narrator (${L('000' + ST[st].trk + '.mp3')}) · ${AR(Math.max(0, Math.ceil(12 - since)))} s left`];
  else if (ph >= 54 && ph < 57.5) cap = ['🤔', 'Decision time: how do we protect Diriyah for future generations?'];
  else if (result) cap = ['🗳️', `The visitor chose “${BTN[choice].n}” → result sound ${L('000' + BTN[choice].trk + '.mp3')} + the lights tell Diriyah in 50 years`];
  else if (ph >= 66) cap = ['🌙', 'The curtain comes down… waiting for the next visitor'];
  else cap = ['🚶', 'The visitor moves on… the system watches where they stop'];
  return { ph, cur, st, since, vx, walking, choice, press, result, track, pkt, cap };
}
function heroSVG(t) {
  const S = heroState(t), hue = t * 1000 / HUE_MS;
  const by = 420;
  const stations = ST.map((s, i) => {
    const on = S.st === i, c = css(hueRGB(hue + i * 40));
    const art = i === 0 ? palace(s.x, by) : i === 1 ? mosque(s.x, by) : wadi(s.x, by);
    return `<g>${on ? `<path d="M${s.x - 26} 92 L${s.x - 190} ${by + 10} L${s.x + 190} ${by + 10} L${s.x + 26} 92z" fill="url(#dyCone)"/>` : ''}
      ${art}
      <rect x="${s.x - 210}" y="70" width="420" height="${by - 66}" fill="#050713" opacity="${on ? 0 : .62}"/>
      <g transform="translate(${s.x} 82)"><path d="M-24 -12 h48 l-10 22 h-28z" fill="#2b2b33"/><circle cy="12" r="9" fill="${on ? '#fff3c4' : '#3a3a44'}"/></g>
      ${on ? `<circle cx="${s.x}" cy="${by + 8}" r="46" fill="${c}" opacity=".4"/><circle cx="${s.x}" cy="${by + 8}" r="14" fill="${c}"/>` : `<circle cx="${s.x}" cy="${by + 8}" r="10" fill="#2a2d3a"/>`}
      ${irMod(s.x, by + 52, on && S.since < 2)}
      ${on && S.since < 2 ? `<path d="M${s.x} ${by + 66} L${s.x - 46} 640 L${s.x + 46} 640z" fill="#ff4d4d" opacity=".22"/>` : ''}
      <rect x="${s.x - 120}" y="${by + 82}" width="240" height="44" rx="8" fill="${on ? '#f0cc7a' : '#2a2416'}" stroke="#8a611f" stroke-width="2"/>
      <text x="${s.x}" y="${by + 112}" class="dyt" style="font-size:${s.n.length > 22 ? 14 : 22}px;fill:${on ? '#2a1a05' : '#c9b48a'}">${AR(i + 1)}. ${s.n}</text>
      ${on ? `<rect x="${s.x - 120}" y="${by + 130}" width="${240 * (1 - S.since / SW)}" height="6" rx="3" fill="#7ee2a8"/>` : ''}</g>`;
  }).join('');
  const pk = S.pkt >= 0 ? (() => { const k = S.pkt, x = lerp(115, 290, k), y = 112 - Math.sin(k * Math.PI) * 70;
    return `<g transform="translate(${x} ${y})"><circle r="26" fill="#7ee2a8" opacity=".3"/><rect x="-18" y="-15" width="36" height="30" rx="6" fill="#7ee2a8"/><text y="9" class="dyt" style="font-size:22px;fill:#06301b;font-family:monospace;direction:ltr">'${ST[S.st].trk}'</text></g>`; })() : '';
  const btns = BTN.map((b, i) => { const lit = S.result && S.choice === i, down = S.press && S.choice === i;
    return `<g transform="translate(${70 + i * 80} 470)"><circle r="30" fill="#222" /><circle r="24" cy="${down ? 2 : -3}" fill="${b.c}" opacity="${lit || i === 0 && S.ph < 3 ? 1 : .55}"/>
      ${lit ? `<circle r="40" fill="none" stroke="${b.c}" stroke-width="4" opacity=".8"/>` : ''}<text y="${60 + (i % 2) * 18}" class="dyt" style="font-size:14px;fill:#e9e2cf">${b.n}</text></g>`; }).join('');
  return `${DEFS}<rect width="1700" height="720" fill="url(#dySky)"/>${stars(60, 1700, 220)}
    <circle cx="1560" cy="52" r="30" fill="#f6e7b0"/><circle cx="1574" cy="44" r="27" fill="#0b1026"/>
    <rect x="0" y="612" width="1700" height="108" fill="#0e1430"/>
    <rect x="392" y="44" width="1300" height="560" rx="16" fill="#0a0c14" stroke="#2a2416" stroke-width="10"/>
    <rect x="410" y="${by}" width="1264" height="18" fill="#3a2a18"/>
    ${stations}
    ${curtain(410, 1674, 62, by + 18, S.cur)}
    <rect x="16" y="44" width="360" height="560" rx="16" fill="#0f1733" stroke="#2e4288" stroke-width="3"/>
    <text x="196" y="30" class="dyt" style="font-size:18px;fill:#9aa8d8">Control unit (behind the model)</text>
    ${esp(30, 60, 170, 120, 'Sensors & lights', S.st >= 0)}${esp(206, 60, 160, 120, 'Sound', S.track > 0)}
    <path d="M115 112 Q 202 30 290 112" stroke="#7ee2a8" stroke-width="2" stroke-dasharray="6 8" fill="none" opacity=".5"/>
    <text x="202" y="${S.pkt >= 0 ? 214 : 214}" class="dyt" style="font-size:15px;fill:#7ee2a8">📶 ESP-NOW, no wires</text>
    ${pk}
    <g transform="translate(110 290)"><rect x="-80" y="-44" width="160" height="88" rx="10" fill="#1b2340" stroke="#3a4a80"/><text y="-14" class="dyt" style="font-size:16px;fill:#9aa8d8">DFPlayer · SD</text>
      <text y="22" class="dyt" style="font-size:26px;fill:${S.track ? '#f0cc7a' : '#56607e'};font-family:monospace;direction:ltr">${S.track ? String(S.track).padStart(4, '0') + '.mp3' : '— — —'}</text></g>
    ${speaker(262, 290, S.track > 0, t, 1.15)}
    <text x="196" y="398" class="dyt" style="font-size:18px;fill:#f0cc7a">Decision buttons</text>
    ${btns}
    ${S.vx !== null ? person(S.vx, 712, '#f6e7c9', S.walking ? t * 9 : 0, .85) : ''}`;
}

/* ---------- مخطط المنظومة ---------- */
const SYS = [
  { k: 'ir', i: '👁️', n: 'IR sensors ×3', x: 150, y: 120, d: 'Detect a visitor standing at each station. GPIO 18, 19 and 23. A LOW reading means “someone is here”.' },
  { k: 'a', i: '🧠', n: 'ESP32 · Sensors & lights', x: 470, y: 250, d: 'Reads the sensors and decides the active station (station 1 has priority), holds it 12 seconds so its narration finishes, and sends the track number wirelessly.' },
  { k: 'pca', i: '🎛️', n: 'PCA9685', x: 150, y: 330, d: 'A 16-channel PWM driver on I2C (SDA 21, SCL 22, address 0x40). Drives 3 RGB LEDs on nine channels with 4096 levels.' },
  { k: 'rgb', i: '🌈', n: 'RGB ×3', x: 150, y: 500, d: 'Rainbow light cycling only at the active station: a new hue every 15 milliseconds.' },
  { k: 'spot', i: '🔦', n: 'Spotlights ×3', x: 470, y: 500, d: 'White light revealing the active station model. GPIO 25, 26 and 27; the others switch off.' },
  { k: 'now', i: '📶', n: 'ESP-NOW', x: 760, y: 250, d: 'Direct wireless link between boards, no router and no wires: one byte (\'2\', \'3\' or \'4\') is enough.' },
  { k: 'b', i: '🧠', n: 'ESP32 · Sound', x: 1050, y: 250, d: 'Receives the station number and plays its track, reads the decision buttons locally, and welcomes visitors automatically.' },
  { k: 'df', i: '🎵', n: 'DFPlayer + speaker', x: 1050, y: 500, d: 'MP3 player from an SD card: numbered tracks 0001…0012. Connected over UART2 (16 and 17) with a 1kΩ resistor.' },
  { k: 'btn', i: '🔘', n: 'Decision buttons ×4', x: 1340, y: 250, d: 'Yellow 33 welcome, green 26 awareness, blue 27 participation, red 25 innovation. INPUT_PULLUP, and one press = one play.' },
  { k: 'cur', i: '🎭', n: 'Board 3 · Curtain & caravan', x: 1340, y: 500, d: 'A third ESP32: a 28BYJ-48 stepper and ULN2003 driver (14, 27, 26, 25) wind a spool that raises the curtain in 10 seconds; at the start it sends “D” so the old door sound plays. It also drives the caravan along a rail in front of the stations with a NEMA17 and a GT2 belt.' },
];
const SYS_L = [['ir', 'a'], ['a', 'pca'], ['pca', 'rgb'], ['a', 'spot'], ['a', 'now'], ['now', 'b'], ['b', 'df'], ['btn', 'b'], ['cur', 'now']];
const SYS_SEQ = ['ir', 'a', 'spot', 'pca', 'rgb', 'now', 'b', 'df', 'btn', 'cur'];
function sysSVG(t, sel) {
  const P = SYS_SEQ.length * 2.2, auto = SYS_SEQ[Math.floor((t % P) / 2.2)];
  const cur = sel || auto;
  const pos = k => SYS.find(s => s.k === k);
  return `${DEFS}<rect width="1490" height="620" rx="24" fill="#0d1430"/>
    <rect x="40" y="40" width="580" height="560" rx="22" fill="none" stroke="#2e4288" stroke-width="3" stroke-dasharray="10 8"/><text x="330" y="74" class="dyt" style="font-size:22px;fill:#9aa8d8">Board 1 · Sensors & lights</text>
    <rect x="900" y="40" width="300" height="560" rx="22" fill="none" stroke="#2e4288" stroke-width="3" stroke-dasharray="10 8"/><text x="1050" y="74" class="dyt" style="font-size:22px;fill:#9aa8d8">Board 2 · Sound & decision</text>
    ${SYS_L.map(([a, b]) => { const A = pos(a), B = pos(b), hot = cur === a || cur === b;
      return `<line x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}" stroke="${hot ? '#f0cc7a' : '#34406e'}" stroke-width="${hot ? 7 : 4}" ${a === 'now' || b === 'now' ? 'stroke-dasharray="14 10"' : ''}/>`; }).join('')}
    ${(() => { const k = (t * .6) % 1, A = pos('a'), B = pos('b'); return `<circle cx="${lerp(A.x, B.x, k)}" cy="${A.y - Math.sin(k * Math.PI) * 60}" r="12" fill="#7ee2a8"/>`; })()}
    ${SYS.map(s => `<g class="dynode" data-k="${s.k}" transform="translate(${s.x} ${s.y})" style="cursor:pointer">
      <circle r="${cur === s.k ? 66 : 58}" fill="${cur === s.k ? '#f0cc7a' : '#1b2550'}" stroke="${cur === s.k ? '#fff3c4' : '#4a5a9a'}" stroke-width="4"/>
      <text y="16" class="dyt" style="font-size:46px">${s.i}</text>
      <text y="${cur === s.k ? 100 : 92}" class="dyt" style="font-size:21px;fill:${cur === s.k ? '#f0cc7a' : '#dfe4f5'};font-weight:800">${s.n}</text></g>`).join('')}`;
}

/* ---------- مختبر الستارة ---------- */
const SEQ = [[1, 0, 0, 0], [1, 1, 0, 0], [0, 1, 0, 0], [0, 1, 1, 0], [0, 0, 1, 0], [0, 0, 1, 1], [0, 0, 0, 1], [1, 0, 0, 1]];
const CP = 29;  // 3 ث جاهز، 10 فتح، 4 انتظار، 10 إغلاق، 2 تم
function curtainState(t, d) {
  const ph = t % CP, mul = 3 / d;    // المدة ثابتة ١٠ ث: التأخير يحدد كم تتحرك فعلًا
  let mode, el = 0, frac, dir = 0;
  if (ph < 3) { mode = 0; frac = 0; }
  else if (ph < 13) { mode = 1; el = ph - 3; frac = el / 10 * mul; dir = 1; }
  else if (ph < 17) { mode = 2; frac = mul; }
  else if (ph < 27) { mode = 3; el = ph - 17; frac = mul * (1 - el / 10); dir = -1; }
  else { mode = 4; frac = 0; }
  const steps = Math.floor(el * 1000 / d);
  const total = mode === 1 || mode === 3 ? steps : mode === 2 ? Math.floor(10000 / d) : 0;
  const vis = Math.floor(ph * 6) % 8, idx = dir > 0 ? vis : dir < 0 ? 7 - vis : -1;
  const ang = (mode === 1 ? steps : mode === 2 ? 10000 / d : mode === 3 ? 10000 / d - steps : 0) / 4096 * 360;
  return { ph, mode, frac, idx, ang, total, steps };
}
const SERIAL = ['SYSTEM READY', 'DOOR SOUND + CURTAIN RISING...', 'CURTAIN UP - DONE', 'CURTAIN LOWERING...', 'CURTAIN DOWN - DONE'];
function curtainSVG(t, d) {
  const S = curtainState(t, d), f = Math.min(1, S.frac);
  return `${DEFS}<rect width="900" height="560" fill="url(#dySky)"/>${stars(25, 900, 120)}
    <rect x="40" y="40" width="560" height="380" rx="10" fill="#0a0c14" stroke="#2a2416" stroke-width="8"/>
    <g opacity="${.25 + .75 * f}">${palace(320, 400, .9)}</g>
    ${curtain(50, 590, 58, 410, f)}
    ${S.frac > 1.02 ? `<text x="320" y="250" class="dyt" style="font-size:30px;fill:#ff7b7b">⚠️ The curtain overshot the top!</text>` : ''}
    <g transform="translate(750 150)"><circle r="78" fill="#3b6fb0" stroke="#9ec5f2" stroke-width="5"/><circle r="46" fill="#9aa8b8"/>
      <g transform="rotate(${S.ang})"><rect x="-6" y="-60" width="12" height="40" rx="4" fill="#f0cc7a"/><circle r="14" fill="#f0cc7a"/></g>
      <text y="112" class="dyt" style="font-size:22px;fill:#dfe4f5">28BYJ-48</text></g>
    <path d="M672 150 Q 640 40 590 40" stroke="#c9b48a" stroke-width="3" fill="none" stroke-dasharray="6 6"/><text x="640" y="30" class="dyt" style="font-size:15px;fill:#c9b48a">Spool</text>
    <g transform="translate(640 330)"><rect width="230" height="150" rx="10" fill="#1d6b3a" stroke="#7ee2a8" stroke-width="3"/>
      <text x="115" y="30" class="dyt" style="font-size:20px;fill:#e9fbe9">ULN2003</text>
      ${[0, 1, 2, 3].map(i => { const on = S.idx >= 0 && SEQ[S.idx][i]; return `<circle cx="${40 + i * 50}" cy="72" r="15" fill="${on ? '#ff4d4d' : '#4a1f1f'}"/>${on ? `<circle cx="${40 + i * 50}" cy="72" r="26" fill="#ff4d4d" opacity=".3"/>` : ''}<text x="${40 + i * 50}" y="112" class="dyt" style="font-size:16px;fill:#e9fbe9;font-family:monospace;direction:ltr">IN${i + 1}</text><text x="${40 + i * 50}" y="134" class="dyt" style="font-size:15px;fill:#b7e8c4;font-family:monospace;direction:ltr">${[14, 27, 26, 25][i]}</text>`; }).join('')}</g>
    <text x="320" y="470" class="dyt" style="font-size:24px;fill:#f0cc7a">${['⏳ Ready… 3 seconds', '🚪▲ Door sound… rising for 10 s', '⏸ Up', '▼ Lowering: 10 s', '✓ Down'][S.mode]}</text>
    <rect x="50" y="490" width="540" height="14" rx="7" fill="#22284a"/><rect x="50" y="490" width="${540 * Math.min(1, S.frac)}" height="14" rx="7" fill="${S.frac > 1.02 ? '#ff7b7b' : '#7ee2a8'}"/>
    <text x="320" y="540" class="dyt" style="font-size:18px;fill:#9aa8d8">Lights slowed down so you can see the sequence: really ${AR(Math.round(1000 / d))} steps per second</text>`;
}

/* ---------- مختبر الحساسات ---------- */
// محاكاة الخوارزمية نفسها: إن انتهت مدة البقاء → اكتشف → إن تغيّرت المحطة فعّلها وابدأ ١٢ ث
const IRP = 36;
function irPresence(ph) {
  const p = [false, false, false];
  const v1 = ph < 2 ? -1 : ph < 8 ? 1 : ph < 10 ? -1 : 2;     // الزائر الأول: محطة ٢ ثم ٣
  const v2 = ph < 20 ? -1 : 0;                                // الزائر الثاني يصل محطة ١ عند ٢٠ ث
  if (v1 >= 0) p[v1] = true; if (v2 >= 0) p[v2] = true;
  return { p, v1, v2 };
}
function irSim(ph, presFn) {
  let last = -1, hold = 0, log = [], act = 0, holdStart = 0;
  for (let x = 0; x <= ph + 1e-9; x += .05) {
    const p = presFn(x);
    if (x >= hold) {
      const s = p[0] ? 1 : p[1] ? 2 : p[2] ? 3 : 0;
      if (s !== last) { last = s; act = s; if (s) { hold = x + HOLD; holdStart = x; } log.push([x, s, p.slice()]); }
    }
  }
  return { act, hold, holdStart, log };
}
function irSVG(t, man) {
  const ph = man ? null : t % IRP;
  const pr = man ? { p: man.p, v1: -1, v2: -1 } : irPresence(ph);
  const sim = man ? man.sim : irSim(ph, x => irPresence(x).p);
  const now = man ? man.now : ph;
  const xs = [680, 420, 160];
  return `${DEFS}<rect width="840" height="520" fill="url(#dySky)"/>${stars(20, 840, 100)}
    <rect x="20" y="60" width="800" height="250" rx="12" fill="#0a0c14" stroke="#2a2416" stroke-width="6"/>
    ${ST.map((s, i) => { const on = sim.act === i + 1, hit = pr.p[i], c = css(hueRGB(now * 1000 / HUE_MS + i * 40));
      const art = i === 0 ? palace(xs[i], 290, .55) : i === 1 ? `<g transform="translate(${xs[i]} 290) scale(.55) translate(${-xs[i]} -290)">${mosque(xs[i], 290)}</g>` : `<g transform="translate(${xs[i]} 290) scale(.55) translate(${-xs[i]} -290)">${wadi(xs[i], 290)}</g>`;
      return `<g>${on ? `<path d="M${xs[i] - 14} 74 L${xs[i] - 115} 300 L${xs[i] + 115} 300 L${xs[i] + 14} 74z" fill="url(#dyCone)"/>` : ''}${art}
        <rect x="${xs[i] - 128}" y="64" width="256" height="242" fill="#050713" opacity="${on ? 0 : .6}"/>
        ${on ? `<circle cx="${xs[i]}" cy="300" r="12" fill="${c}"/><circle cx="${xs[i]}" cy="300" r="40" fill="${c}" opacity=".3"/>` : ''}
        ${irMod(xs[i], 336, hit, 1.1)}${hit ? `<path d="M${xs[i]} 350 L${xs[i] - 34} 470 L${xs[i] + 34} 470z" fill="#ff4d4d" opacity=".25"/>` : ''}
        <text x="${xs[i]}" y="40" class="dyt" style="font-size:${s.n.length > 22 ? 14 : 22}px;fill:${on ? '#f0cc7a' : '#8f98b8'}">${AR(i + 1)}. ${s.n}</text>
        ${hit ? person(xs[i] + (pr.v2 === i ? -40 : 0), 505, pr.v2 === i ? '#cfe3ff' : '#f6e7c9', 0, .9) : ''}</g>`; }).join('')}`;
}

/* ---------- مختبر الإضاءة ---------- */
function rgbView(t, ms, st, frozen) {
  const hue = frozen != null ? frozen : Math.floor(t * 1000 / ms) % 360;
  const [r, g, b, reg] = hueRGB(hue);
  return { hue, r, g, b, reg };
}
function rgbSVG(V, st) {
  const c = css([V.r, V.g, V.b]);
  const chs = ST[st].ch;    // [R, G, B]
  const vals = {}; vals[chs[0]] = V.r; vals[chs[1]] = V.g; vals[chs[2]] = V.b;
  return `${DEFS}<rect width="820" height="520" fill="#0d1226"/>
    <g transform="translate(250 220)"><circle r="190" fill="${c}" opacity=".18"/><circle r="120" fill="${c}" opacity=".35"/>
      <path d="M-46 40 v-80 a46 46 0 0 1 92 0 v80z" fill="${c}" stroke="#fff" stroke-width="3" opacity=".95"/><rect x="-54" y="40" width="108" height="18" rx="4" fill="#ccc"/>
      ${[-33, -11, 11, 33].map((x, i) => `<line x1="${x}" y1="58" x2="${x}" y2="${i === 3 ? 150 : 135}" stroke="#bbb" stroke-width="5"/>`).join('')}
      <text y="200" class="dyt" style="font-size:22px;fill:#dfe4f5">Station ${AR(st + 1)} RGB · common cathode</text></g>
    <g transform="translate(520 40)"><rect width="270" height="440" rx="14" fill="#1d4f8a" stroke="#9ec5f2" stroke-width="3"/>
      <text x="135" y="36" class="dyt" style="font-size:22px;fill:#fff">PCA9685 · 0x40</text>
      ${Array.from({ length: 12 }, (_, i) => { const v = vals[i], on = v != null;
        return `<g transform="translate(24 ${62 + i * 31})"><text x="0" y="16" style="font:700 15px monospace;direction:ltr;fill:${on ? '#fff' : '#7f9cc4'}">CH${String(i).padStart(2, '0')}</text>
          <rect x="62" y="3" width="150" height="16" rx="8" fill="#123a66"/>${on ? `<rect x="62" y="3" width="${150 * v / 4095}" height="16" rx="8" fill="${i === chs[0] ? '#ff5a5a' : i === chs[1] ? '#3ddc84' : '#4f8dff'}"/>` : ''}
          <text x="222" y="16" style="font:700 13px monospace;direction:ltr;fill:${on ? '#fff' : '#5c7aa6'}">${on ? v : (i >= 9 ? '—' : '0')}</text></g>`; }).join('')}</g>`;
}

/* ---------- مختبر ESP-NOW ---------- */
const NP = 12;
function nowState(t, man) {
  if (man) { const k = (t - man.t0); return { st: man.st, k, ph: k }; }
  const ph = t % NP, st = Math.floor(ph / 4), k = ph % 4;
  return { st, k, ph };
}
function nowSVG(t, S) {
  const flying = S.k < .9, kk = S.k / .9, x = lerp(250, 610, kk), y = 200 - Math.sin(kk * Math.PI) * 120;
  const playing = S.k >= .9 && S.k < 3.8;
  return `${DEFS}<rect width="860" height="520" fill="#0d1226"/>
    ${esp(60, 140, 200, 140, 'Sensors & lights', true)}${esp(600, 140, 200, 140, 'Sound', playing)}
    ${ST.map((s, i) => `${irMod(110 + i * 50, 340, S.st === i && S.k < 1.5, .7)}`).join('')}<text x="160" y="390" class="dyt" style="font-size:18px;fill:#9aa8d8">The three IR sensors</text>
    <path d="M250 200 Q 430 60 610 200" stroke="#7ee2a8" stroke-width="3" stroke-dasharray="10 10" fill="none" opacity=".5"/>
    <text x="430" y="250" style="font:700 18px monospace;direction:ltr;fill:#7ee2a8;text-anchor:middle">broadcast FF:FF:FF:FF:FF:FF</text>
    ${flying ? `<g transform="translate(${x} ${y})"><circle r="40" fill="#7ee2a8" opacity=".25"/><rect x="-30" y="-24" width="60" height="48" rx="8" fill="#7ee2a8"/><text y="12" style="font:800 32px monospace;direction:ltr;fill:#06301b;text-anchor:middle">'${ST[S.st].trk}'</text></g>` : ''}
    ${speaker(700, 380, playing, t, 1.4)}
    <rect x="560" y="440" width="280" height="56" rx="10" fill="#1b2340" stroke="#3a4a80"/>
    <text x="700" y="477" style="font:800 26px monospace;direction:ltr;fill:${playing ? '#f0cc7a' : '#56607e'};text-anchor:middle">${playing ? '000' + ST[S.st].trk + '.mp3 ▶' : 'Waiting…'}</text>
    <text x="160" y="470" class="dyt" style="font-size:20px;fill:#f0cc7a">activateStation(${S.st + 1})</text>`;
}

/* ---------- مختبر أزرار القرار ---------- */
// سيناريو تلقائي: كل عنصر [الزر، بداية الضغط، نهايته]
const DP = 14, DSCRIPT = [[1, 1, 3.2], [2, 5, 5.4], [3, 7.5, 9.5], [3, 9.9, 10.3], [0, 12, 12.4]];
function decSignal(btn, x, script) { return script.some(([b, a, z]) => b === btn && x >= a && x < z); }
function decSVG(t, sel, script, now) {
  const W = 760, span = 6;
  const pts = [], edges = [];
  for (let i = 0; i <= 240; i++) { const x = now - span + span * i / 240; const low = x >= 0 && decSignal(sel, x, script);
    pts.push(`${40 + (W - 150) * i / 240},${low ? 300 : 210}`); }
  script.forEach(([b, a]) => { if (b === sel && a > now - span && a <= now) edges.push(40 + (W - 150) * (a - now + span) / span); });
  return `<rect width="${W}" height="420" rx="16" fill="#0d1226"/>
    <text x="${W / 2}" y="44" class="dyt" style="font-size:24px;fill:#dfe4f5">GPIO${BTN[sel].pin} signal · ${BTN[sel].n} button</text>
    <line x1="40" y1="210" x2="${W - 110}" y2="210" stroke="#2a3360" stroke-dasharray="4 6"/><line x1="40" y1="300" x2="${W - 110}" y2="300" stroke="#2a3360" stroke-dasharray="4 6"/>
    <text x="${W - 96}" y="216" style="font:700 20px monospace;direction:ltr;fill:#7f8bb8">HIGH</text><text x="${W - 96}" y="306" style="font:700 20px monospace;direction:ltr;fill:#7f8bb8">LOW</text>
    <polyline points="${pts.join(' ')}" fill="none" stroke="${BTN[sel].c}" stroke-width="6" stroke-linejoin="round"/>
    ${edges.map(x => `<g transform="translate(${x} 300)"><circle r="12" fill="#f0cc7a"/><path d="M0 -24 v-50" stroke="#f0cc7a" stroke-width="3"/><text y="-84" style="font:800 20px monospace;direction:ltr;fill:#f0cc7a;text-anchor:middle">▶ 000${BTN[sel].trk}.mp3</text></g>`).join('')}
    <text x="${W / 2}" y="380" class="dyt" style="font-size:20px;fill:#9aa8d8">Gold dot = the moment of a new press only · holding the button does not replay</text>`;
}

/* ---------- الأنواع ---------- */
const wrapCap = id => `<div class="dycap" id="${id}"><span class="i"></span><span class="tx"></span></div>`;
window.DECK_TYPES = Object.assign(window.DECK_TYPES || {}, {
  dyhero: s => `<div class="slide dark dyhero">
      <div class="kicker">${s.kicker}</div><button class="dysnd ix" id="dysnd">🔇 Sound off</button>
      <h1 class="dyh1">${s.title}</h1>
      <div class="dygif dyherow"><svg viewBox="0 0 1700 720" class="dysvg" id="dyhs"></svg>${wrapCap('dyhc')}</div></div>`,

  dysystem: s => `<div class="slide light">
      <div class="kicker">🧩 The parts and how they connect</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dysys">
        <div class="dygif ix"><svg viewBox="0 0 1490 620" class="dysvg" id="dyss"></svg></div>
        <div class="dyinfo" id="dysi"></div>
      </div></div>`,

  dycurtain: s => `<div class="slide light">
      <div class="kicker">🎭 The curtain · 28BYJ-48 stepper + ULN2003</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab">
        <div class="dygif ix"><svg viewBox="0 0 900 560" class="dysvg" id="dycs"></svg></div>
        <div class="dyside ix">
          <div class="dyseq" id="dyseq">${SEQ.map((r, i) => `<div class="r" data-i="${i}"><b>${AR(i + 1)}</b>${r.map(v => `<i class="${v ? 'on' : ''}">${v}</i>`).join('')}</div>`).join('')}</div>
          <label class="dysl"><span>⏱️ STEP_DELAY_MS = <b id="dycdv">3</b></span><input type="range" id="dycd" min="2" max="6" value="3" step="1"></label>
          <div class="dyfacts"><div><span>Steps in 10 s</span><b id="dycf1"></b></div><div class="g"><span>Shaft turns</span><b id="dycf2"></b></div></div>
          <div class="dyser" id="dycser"></div>
        </div></div></div>`,

  dyir: s => `<div class="slide light">
      <div class="kicker">👁️ Detecting the visitor · 3 IR sensors</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab">
        <div class="dygif ix"><svg viewBox="0 0 840 520" class="dysvg" id="dyis"></svg></div>
        <div class="dyside ix">
          <div class="dypins" id="dyip"></div>
          <div class="dydec" id="dyid"></div>
          <div class="dyhold"><span>HOLD time</span><div class="bar"><i id="dyih"></i></div><b id="dyihv"></b></div>
          <div class="dybtns">${ST.map((x, i) => `<button class="dyb" data-p="${i}">🚶 Visitor at ${AR(i + 1)}</button>`).join('')}<button class="dyb ghost" data-p="auto">▶ Auto</button></div>
          <div class="dylog" id="dyil"></div>
        </div></div></div>`,

  dyrgb: s => `<div class="slide light">
      <div class="kicker">🌈 Lighting · PCA9685 + RGB</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab">
        <div class="dygif ix"><svg viewBox="0 0 820 520" class="dysvg" id="dyrs"></svg></div>
        <div class="dyside ix">
          <div class="dywheel"><div class="w"></div><div class="p" id="dyrp"></div><div class="c"><b id="dyrh"></b><span>hue</span></div></div>
          <div class="dyfacts"><div><span>region</span><b id="dyrr"></b></div><div class="g"><span>Full cycle</span><b id="dyrc"></b></div></div>
          <label class="dysl"><span>⏱️ Every <b id="dyrmv">15</b> ms: hue +1</span><input type="range" id="dyrm" min="5" max="40" value="15" step="1"></label>
          <div class="dybtns">${ST.map((x, i) => `<button class="dyb ${i ? '' : 'on'}" data-s="${i}">Station ${AR(i + 1)}</button>`).join('')}<button class="dyb ghost" id="dyrf">⏸ Freeze</button></div>
        </div></div></div>`,

  dynow: s => `<div class="slide light">
      <div class="kicker">📶 Two boards talking without wires · ESP-NOW</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab">
        <div class="dygif ix"><svg viewBox="0 0 860 520" class="dysvg" id="dyns"></svg></div>
        <div class="dyside ix">
          <div class="dytracks" id="dynt">${TRACKS.map((x, i) => `<div data-t="${i + 1}" class="${i > 7 ? 'new' : ''}"><button class="dyplay" data-audio="${SND(i + 1)}" data-n="${i + 1}">▶</button><code>${String(i + 1).padStart(4, '0')}.mp3</code><span>${x}</span></div>`).join('')}</div>
          <div class="dybtns">${ST.map((x, i) => `<button class="dyb" data-s="${i}">Send '${x.trk}'</button>`).join('')}</div>
          <div class="dyfacts"><div><span>Message size</span><b>1 byte</b></div><div class="g"><span>Router?</span><b>Not needed</b></div></div>
        </div></div></div>`,

  dydecision: s => `<div class="slide light">
      <div class="kicker">🗳️ Decision time · 4 buttons</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab">
        <div class="dyside dyarc ix">
          <div class="dypanel">${BTN.map((b, i) => `<button class="dyarcade" data-b="${i}" data-audio="${SND(b.trk)}" style="--c:${b.c}"><i></i><b>${b.n}</b><small>GPIO ${b.pin}</small></button>`).join('')}</div>
          <div class="dyres" id="dyres"><code></code><span></span></div>
        </div>
        <div class="dygif ix"><svg viewBox="0 0 760 420" class="dysvg" id="dyds"></svg></div>
      </div></div>`,

  dyevolve: s => `<div class="slide light">
      <div class="kicker">🛠️ How we built it · reaching the final design</div>
      <h2 class="title" style="margin-bottom:18px">${s.title}</h2>
      <div class="dyevo">${s.items.map((it, i) => `<div class="e f ${i === s.items.length - 1 ? 'fin' : ''}"><div class="n">${it.v}</div><h3>${it.h}</h3><p>${it.b}</p>${it.why ? `<div class="why">${it.why}</div>` : ''}</div>`).join('<div class="arr f">←</div>')}</div>
      ${s.img ? `<div class="dyimg f"><img src="${s.img}" alt=""><span>${s.cap}</span></div>` : ''}</div>`,
});

/* ---------- الربط والحركة ---------- */
function runLoop(draw, period) {
  let raf = 0, t0 = 0;
  const tick = now => { t0 = t0 || now; if (!window.DY_HOLD) draw((now - t0) / 1000); raf = requestAnimationFrame(tick); };
  raf = requestAnimationFrame(tick);
  window.DY_ANIM = { draw, period };
  window.DECK_CLEANUP.push(() => { cancelAnimationFrame(raf); window.DY_ANIM = null; });
}
const setCap = (el, [i, tx]) => { el.querySelector('.i').textContent = i; el.querySelector('.tx').textContent = tx; };

window.DECK_BIND = Object.assign(window.DECK_BIND || {}, {
  dyhero(sl) {
    const svg = sl.querySelector('#dyhs'), cap = sl.querySelector('#dyhc');
    const btn = sl.querySelector('#dysnd'); let on = false, lastTrk = 0;
    btn.onclick = () => { on = !on; btn.textContent = on ? '🔊 Sound on' : '🔇 Sound off'; btn.classList.toggle('on', on); if (!on) stopSnd(); lastTrk = 0; };
    runLoop(t => { svg.innerHTML = heroSVG(t); const S = heroState(t); setCap(cap, S.cap);
      if (on && S.track && S.track !== lastTrk) playSnd(S.track); lastTrk = S.track; }, HP);
    window.DECK_CLEANUP.push(stopSnd);
  },
  dysystem(sl) {
    const svg = sl.querySelector('#dyss'), info = sl.querySelector('#dysi');
    let sel = null, lastK = '';
    const show = k => { if (k === lastK) return; lastK = k; const s = SYS.find(x => x.k === k);
      info.innerHTML = `<div class="ic">${s.i}</div><h3>${s.n}</h3><p>${s.d}</p>`; };
    svg.addEventListener('click', e => { const g = e.target.closest('.dynode'); if (g) { sel = g.dataset.k; } });
    runLoop(t => { const P = SYS_SEQ.length * 2.2; svg.innerHTML = sysSVG(t, sel); show(sel || SYS_SEQ[Math.floor((t % P) / 2.2)]); }, SYS_SEQ.length * 2.2);
  },
  dycurtain(sl) {
    const svg = sl.querySelector('#dycs'), rng = sl.querySelector('#dycd'), rows = sl.querySelectorAll('.dyseq .r'), ser = sl.querySelector('#dycser');
    let d = 3;
    const facts = () => { sl.querySelector('#dycdv').textContent = d; sl.querySelector('#dycf1').textContent = AR(Math.floor(10000 / d));
      sl.querySelector('#dycf2').textContent = AR((10000 / d / 4096).toFixed(2)) + ' turns'; };
    rng.oninput = () => { d = +rng.value; facts(); }; facts();
    runLoop(t => { svg.innerHTML = curtainSVG(t, d); const S = curtainState(t, d);
      rows.forEach((r, i) => r.classList.toggle('now', i === S.idx));
      ser.innerHTML = SERIAL.slice(0, [1, 2, 3, 4, 5][S.mode]).map((l, i, a) => `<div class="${i === a.length - 1 ? 'last' : ''}">${l}</div>`).join(''); }, CP);
  },
  dyir(sl) {
    const svg = sl.querySelector('#dyis');
    let man = null, tNow = 0;
    const pins = sl.querySelector('#dyip'), dec = sl.querySelector('#dyid'), hb = sl.querySelector('#dyih'), hv = sl.querySelector('#dyihv'), lg = sl.querySelector('#dyil');
    sl.querySelectorAll('.dyb').forEach(b => b.onclick = () => {
      if (b.dataset.p === 'auto') { man = null; return; }
      if (!man) man = { p: [false, false, false], t0: tNow, events: [] };
      const i = +b.dataset.p; man.p[i] = !man.p[i]; man.events.push([tNow - man.t0, man.p.slice()]);
      b.classList.toggle('on', man.p[i]);
    });
    const presMan = x => { let p = [false, false, false]; man.events.forEach(([a, q]) => { if (x >= a) p = q; }); return p; };
    runLoop(t => {
      tNow = t;
      let view;
      if (man) { const now = t - man.t0; const sim = irSim(now, presMan); view = { p: presMan(now), sim, now }; svg.innerHTML = irSVG(t, view); }
      else { const ph = t % IRP; view = { p: irPresence(ph).p, sim: irSim(ph, x => irPresence(x).p), now: ph }; svg.innerHTML = irSVG(t); }
      if (!man) sl.querySelectorAll('.dyb[data-p]').forEach(b => b.classList.remove('on'));
      const { p, sim, now } = view, holding = now < sim.hold && sim.act;
      pins.innerHTML = ST.map((s, i) => `<div class="${p[i] ? 'lo' : ''}"><code>GPIO${s.ir}</code><b>${p[i] ? 'LOW' : 'HIGH'}</b><span>${p[i] ? 'visitor' : 'nobody'}</span></div>`).join('');
      const ignored = holding && p.some((v, i) => v && i + 1 !== sim.act);
      dec.innerHTML = sim.act ? `<b>Active station: ${AR(sim.act)}</b><span>${ignored ? '🔒 Another sensor sees a visitor… but this station has not finished speaking, so it is ignored for now' : p.filter(Boolean).length > 1 ? '⚖️ More than one visitor: the lower station number wins' : '✓ Spotlight + RGB + its narration'}</span>` : '<b>No active station</b><span>All lights off… waiting for a visitor</span>';
      const left = holding ? Math.max(0, sim.hold - now) : 0;
      hb.style.width = (left / HOLD * 100) + '%'; hv.textContent = holding ? AR(left.toFixed(1)) + ' s' : '—';
      lg.innerHTML = sim.log.slice(-4).map(([x, s]) => `<div><code>${AR(x.toFixed(1))} s</code> ${s ? 'Active station: ' + AR(s) : 'No visitor — all off'}</div>`).join('');
    }, IRP);
  },
  dyrgb(sl) {
    const svg = sl.querySelector('#dyrs'), rng = sl.querySelector('#dyrm'), fz = sl.querySelector('#dyrf');
    let ms = 15, st = 0, frozen = null, last = 0;
    rng.oninput = () => { ms = +rng.value; sl.querySelector('#dyrmv').textContent = ms; };
    sl.querySelectorAll('.dyb[data-s]').forEach(b => b.onclick = () => { st = +b.dataset.s; sl.querySelectorAll('.dyb[data-s]').forEach(x => x.classList.toggle('on', x === b)); });
    fz.onclick = () => { frozen = frozen == null ? last : null; fz.textContent = frozen == null ? '⏸ Freeze' : '▶ Play'; };
    runLoop(t => { const V = rgbView(t, ms, st, frozen); last = V.hue; svg.innerHTML = rgbSVG(V, st);
      sl.querySelector('#dyrp').style.transform = `rotate(${V.hue}deg)`; sl.querySelector('#dyrh').textContent = AR(V.hue) + '°';
      sl.querySelector('#dyrr').textContent = AR(V.reg); sl.querySelector('#dyrc').textContent = AR((360 * ms / 1000).toFixed(1)) + ' s'; }, 360 * 15 / 1000);
  },
  dynow(sl) {
    const svg = sl.querySelector('#dyns'), rows = sl.querySelectorAll('.dytracks div');
    let man = null, tNow = 0;
    sl.querySelectorAll('.dyb[data-s]').forEach(b => b.onclick = () => { man = { st: +b.dataset.s, t0: tNow }; playSnd(ST[+b.dataset.s].trk); });
    sl.querySelectorAll('.dyplay').forEach(b => b.onclick = () => playSnd(+b.dataset.n));
    window.DECK_CLEANUP.push(stopSnd);
    runLoop(t => { tNow = t; let S = nowState(t, man); if (man && S.k > 4) { man = null; S = nowState(t); }
      svg.innerHTML = nowSVG(t, S); const tr = S.k >= .9 && S.k < 3.8 ? ST[S.st].trk : 0;
      rows.forEach(r => r.classList.toggle('on', +r.dataset.t === tr)); }, NP);
  },
  dydecision(sl) {
    const svg = sl.querySelector('#dyds'), res = sl.querySelector('#dyres');
    let man = null, tNow = 0, sel = 1;
    const btns = sl.querySelectorAll('.dyarcade');
    window.DECK_CLEANUP.push(stopSnd);
    btns.forEach(b => {
      const i = +b.dataset.b;
      const down = e => { e.preventDefault(); playSnd(BTN[i].trk); if (!man) man = { t0: tNow, script: [] }; sel = i; man.script.push([i, tNow - man.t0, 1e9]); };
      const up = () => { if (!man) return; const s = man.script.filter(x => x[0] === i && x[2] === 1e9).pop(); if (s) s[2] = tNow - man.t0; };
      b.addEventListener('pointerdown', down); b.addEventListener('pointerup', up); b.addEventListener('pointerleave', up);
    });
    runLoop(t => {
      tNow = t;
      let script, now;
      if (man) { script = man.script; now = t - man.t0; } else { script = DSCRIPT; now = t % DP; const cur = DSCRIPT.filter(x => now >= x[1]).pop(); sel = cur ? cur[0] : 1; }
      svg.innerHTML = decSVG(t, sel, script, now);
      btns.forEach((b, i) => b.classList.toggle('down', decSignal(i, now, script)));
      const lastPress = script.filter(x => now >= x[1]).pop();
      if (lastPress && now - lastPress[1] < 4) { const b = BTN[lastPress[0]]; res.style.setProperty('--c', b.c); res.classList.add('on');
        res.querySelector('code').textContent = `▶ 000${b.trk}.mp3`; res.querySelector('span').textContent = `${b.n}: ${b.r}`; }
      else { res.classList.remove('on'); res.querySelector('code').textContent = '…'; res.querySelector('span').textContent = 'Press a button (or wait for the auto demo)'; }
    }, DP);
  },
});

/* =====================================================================
   الإضافات الجديدة (الإصدار ٢)
   dyextra: الراوي يفهم الزائر (يد ثابتة أمام الحساس ⇐ شرح إضافي)
   dyfuture: الدرعية بعد ٥٠ سنة (الإضاءة تحكي نتيجة القرار)
   ===================================================================== */
function hand(x, y, k = 1) {
  return `<g transform="translate(${x} ${y}) scale(${k})"><rect x="-34" y="-10" width="68" height="70" rx="22" fill="#e9c9a3"/>
    ${[-26, -9, 8, 25].map((fx, i) => `<rect x="${fx - 7}" y="${-58 + Math.abs(i - 1.5) * 6}" width="15" height="60" rx="7.5" fill="#e9c9a3"/>`).join('')}
    <rect x="30" y="0" width="14" height="44" rx="7" transform="rotate(-35 37 22)" fill="#e9c9a3"/><rect x="-26" y="58" width="52" height="60" fill="#3a6fb0"/></g>`;
}
// نفس منطق الكود: ملخص ١٢ ث، ثم إن بقيت اليد ⇐ شرح إضافي ٢٠ ث
const XP = 52;
function extraSim(ph, pres) {
  let state = 'idle', until = 0;
  const log = [];
  for (let x = 0; x <= ph + 1e-9; x += .05) {
    const p = pres(x);
    if (state === 'idle' && p) { state = 'sum'; until = x + 12; log.push([x, 'sum']); }
    else if (state === 'sum' && x >= until) {
      if (p) { state = 'extra'; until = x + 20; log.push([x, 'extra']); }
      else { state = 'idle'; log.push([x, 'off']); }
    } else if (state === 'extra' && x >= until) { state = p ? 'done' : 'idle'; log.push([x, 'off']); }
    else if (state === 'done' && !p) state = 'idle';
  }
  return { state, until, log };
}
// السيناريو التلقائي: الدورة الأولى تبقى اليد، والثانية تُرفع بعد ٥ ث
function extraPres(ph) { return (ph >= 1 && ph < 34) || (ph >= 35 && ph < 40); }
function extraSVG(t, view) {
  const { p, sim, now } = view, on = sim.state === 'sum' || sim.state === 'extra';
  const c = css(hueRGB(now * 1000 / HUE_MS));
  return `${DEFS}<rect width="900" height="520" fill="url(#dySky)"/>${stars(22, 900, 120)}
    <rect x="160" y="40" width="580" height="330" rx="12" fill="#0a0c14" stroke="#2a2416" stroke-width="6"/>
    ${on ? `<path d="M430 54 L280 360 L620 360 L470 54z" fill="url(#dyCone)"/>` : ''}
    ${palace(450, 350, .95)}<rect x="166" y="46" width="568" height="318" fill="#050713" opacity="${on ? 0 : .6}"/>
    ${on ? `<circle cx="450" cy="352" r="14" fill="${c}"/><circle cx="450" cy="352" r="44" fill="${c}" opacity=".3"/>` : ''}
    ${irMod(450, 400, p, 1.3)}${p ? `<path d="M450 420 L410 470 L490 470z" fill="#ff4d4d" opacity=".3"/>` + hand(450, 470, .9) : ''}
    <text x="450" y="30" class="dyt" style="font-size:22px;fill:#f0cc7a">1. Salwa Palace</text>`;
}
function futureState(t, man) {
  const P = 16;
  let ph, pol;
  if (man) { ph = t - man.t0; pol = man.pol; if (ph > 15) return null; }
  else { ph = t % P; pol = ['a', 'p', 'i'][Math.floor(t / P) % 3]; }
  const lv = [0, 0, 0], rgb = [[0, 0, 0], [0, 0, 0], [0, 0, 0]];
  let phase;
  if (ph < 4) {
    phase = 'neglect'; const k = ph / 4, base = 255 * (1 - k);
    for (let i = 0; i < 3; i++) {
      const r = Math.abs(Math.sin(Math.floor(t * 20) * 12.9898 + i * 78.233) * 43758.5453) % 1;   // ارتعاش «عشوائي» ثابت لكل لحظة
      lv[i] = r < .25 ? base * r * 2 : base; rgb[i] = [4095 * (1 - k), 900 * (1 - k), 0];
    }
  } else if (ph < 14) {
    phase = 'restore'; const k = (ph - 4) / 10, ms = (ph - 4) * 1000;
    for (let i = 0; i < 3; i++) {
      if (pol === 'a') { lv[i] = 255 * k; rgb[i] = [4095 * k, 1500 * k, 0]; }
      else if (pol === 'p') { const ki = clamp((k - i * .25) / .3, 0, 1); lv[i] = 255 * ki; rgb[i] = [0, 4095 * ki, 600 * ki]; }
      else if (k < .6) { const cur = Math.floor(ms / 400) % 3; rgb[i] = i === cur ? [0, 600, 4095] : [0, 0, 0]; lv[i] = 40; }
      else { const kk = (k - .6) / .4; lv[i] = 255 * kk; rgb[i] = [0, 1200, 4095]; }
    }
  } else phase = 'end';
  return { ph, pol, lv, rgb, phase };
}
const FUT_MSG = { a: '🟢 Awareness: knowledge spreads, all stations return together', p: '🔵 Participation: every visitor adds… station by station', i: '🔴 Innovation: technology scans and guards… then the light returns' };
function futureSVG(F) {
  const xs = [700, 450, 200];
  const year = F.phase === 'neglect' ? 2026 + Math.round(F.ph / 4 * 50) : 2076;
  const msg = F.phase === 'neglect' ? 'If we neglect it… the mud erodes and the light fades' : F.phase === 'restore' ? FUT_MSG[F.pol] : 'Diriyah endures for generations ✓';
  return `${DEFS}<rect width="900" height="520" fill="url(#dySky)"/>${stars(22, 900, 110)}
    <rect x="20" y="70" width="860" height="330" rx="12" fill="#0a0c14" stroke="#2a2416" stroke-width="6"/>
    ${ST.map((s, i) => { const x = xs[i], o = F.lv[i] / 255, c = css(F.rgb[i]);
      const art = i === 0 ? palace(x, 380, .62) : `<g transform="translate(${x} 380) scale(.6) translate(${-x} -380)">${i === 1 ? mosque(x, 380) : wadi(x, 380)}</g>`;
      return `${o > .05 ? `<path d="M${x - 12} 84 L${x - 120} 390 L${x + 120} 390 L${x + 12} 84z" fill="url(#dyCone)" opacity="${o}"/>` : ''}${art}
        <rect x="${x - 125}" y="76" width="250" height="318" fill="#050713" opacity="${.78 * (1 - o)}"/>
        <circle cx="${x}" cy="384" r="12" fill="${c}"/><circle cx="${x}" cy="384" r="40" fill="${c}" opacity=".3"/>
        <text x="${x}" y="430" class="dyt" style="font-size:${s.n.length > 22 ? 14 : 21}px;fill:#c9b48a">${s.n}</text>`; }).join('')}
    <text x="450" y="50" style="font:900 40px monospace;direction:ltr;text-anchor:middle;fill:${F.phase === 'neglect' ? '#ff8a6b' : '#f0cc7a'}">${year}</text>
    <text x="450" y="490" class="dyt" style="font-size:26px;fill:${F.phase === 'neglect' ? '#ff8a6b' : '#7ee2a8'}">${msg}</text>`;
}
const POL = [{ k: 'a', b: 1 }, { k: 'p', b: 2 }, { k: 'i', b: 3 }];
const XLOG = { sum: 'Station active ⇒ summary (0002)', extra: "Visitor is interested ⇒ 'A' ⇒ extra narration (0009)", off: 'Done — lights off' };
Object.assign(window.DECK_TYPES, {
  dyextra: s => `<div class="slide light">
      <div class="kicker">🆕 New 1 · The narrator understands the visitor</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab">
        <div class="dygif ix"><svg viewBox="0 0 900 520" class="dysvg" id="dyxs"></svg></div>
        <div class="dyside ix">
          <div class="dyxt"><div class="seg s1"><i id="dyx1"></i><b>Summary</b><span>0002 · 12 s</span></div><div class="seg s2"><i id="dyx2"></i><b>Extra narration</b><span>0009 · 20 s</span></div></div>
          <div class="dydec" id="dyxd"></div>
          <div class="dybtns"><button class="dyb" id="dyxh">✋ Place hand</button><button class="dyb ghost" id="dyxa">▶ Auto</button></div>
          <div class="dylog" id="dyxl"></div>
        </div></div></div>`,
  dyfuture: s => `<div class="slide light">
      <div class="kicker">🆕 New 2 · Diriyah in 50 years</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab">
        <div class="dygif ix"><svg viewBox="0 0 900 520" class="dysvg" id="dyfs"></svg></div>
        <div class="dyside ix">
          <div class="dyphase"><div id="dyf1"><b>1</b> 4 s “neglect”: the light flickers and fades</div><div id="dyf2"><b>2</b> 10 s “restore” in the style of the choice</div></div>
          <div class="dypanel dypol">${POL.map(p => `<button class="dyarcade" data-p="${p.k}" data-audio="${SND(BTN[p.b].trk)}" style="--c:${BTN[p.b].c}"><i></i><b>${BTN[p.b].n}</b><small>'${p.k}'</small></button>`).join('')}</div>
          <div class="dyfacts"><div><span>From the sound board</span><b>'a' · 'p' · 'i'</b></div><div class="g"><span>To the light board</span><b>ESP-NOW</b></div></div>
        </div></div></div>`,
});
Object.assign(window.DECK_BIND, {
  dyextra(sl) {
    const svg = sl.querySelector('#dyxs'), hb = sl.querySelector('#dyxh'), d = sl.querySelector('#dyxd'), lg = sl.querySelector('#dyxl');
    const b1 = sl.querySelector('#dyx1'), b2 = sl.querySelector('#dyx2');
    let man = null, tNow = 0, lastState = '';
    hb.onclick = () => {
      if (!man) man = { t0: tNow, ev: [] };
      const p = !man.ev.length || !man.ev[man.ev.length - 1][1];
      man.ev.push([tNow - man.t0, p]); hb.textContent = p ? '🖐️ Lift hand' : '✋ Place hand'; hb.classList.toggle('on', p);
    };
    sl.querySelector('#dyxa').onclick = () => { man = null; hb.textContent = '✋ Place hand'; hb.classList.remove('on'); stopSnd(); };
    window.DECK_CLEANUP.push(stopSnd);
    runLoop(t => {
      tNow = t;
      const pres = man ? (x => { let p = false; man.ev.forEach(([a, q]) => { if (x >= a) p = q; }); return p; }) : extraPres;
      const now = man ? t - man.t0 : t % XP, sim = extraSim(now, pres), p = pres(now);
      svg.innerHTML = extraSVG(t, { p, sim, now });
      if (man && sim.state !== lastState) { if (sim.state === 'sum') playSnd(2); else if (sim.state === 'extra') playSnd(9); }
      lastState = sim.state;
      const lastSum = [...sim.log].reverse().find(x => x[1] === 'sum'), t0 = lastSum ? lastSum[0] : now;
      const ex = sim.log.find(x => x[1] === 'extra' && x[0] >= t0);
      b1.style.width = (lastSum ? Math.min(1, (now - t0) / 12) * 100 : 0) + '%';
      b2.style.width = (ex ? Math.min(1, (now - ex[0]) / 20) * 100 : 0) + '%';
      const left = AR(Math.max(0, Math.ceil(sim.until - now)));
      d.innerHTML = sim.state === 'sum' ? `<b>Summary playing…</b><span>${p ? '✋ Hand still there' : '🖐️ Hand lifted'} · the system decides in ${left} s</span>`
        : sim.state === 'extra' ? `<b>🧠 Decision: the visitor is interested</b><span>Hand stayed after the summary ⇒ extra narration 0009 · ${left} s</span>`
        : sim.state === 'done' ? '<b>✓ Extra narration finished</b><span>Lift your hand to start a new visit</span>'
        : lastSum ? '<b>🧠 Decision: the summary is enough</b><span>Hand lifted before the summary ended ⇒ no extra narration</span>'
        : '<b>Waiting for a visitor…</b><span>Put your hand in front of the sensor (or wait for the auto demo)</span>';
      lg.innerHTML = sim.log.slice(-3).map(([x, k]) => `<div><code>${AR(x.toFixed(1))} s</code> ${XLOG[k]}</div>`).join('');
    }, XP);
  },
  dyfuture(sl) {
    const svg = sl.querySelector('#dyfs'), f1 = sl.querySelector('#dyf1'), f2 = sl.querySelector('#dyf2');
    let man = null, tNow = 0;
    sl.querySelectorAll('.dypol .dyarcade').forEach(b => b.addEventListener('pointerdown', e => {
      e.preventDefault(); man = { t0: tNow, pol: b.dataset.p }; playSnd(BTN[POL.find(x => x.k === b.dataset.p).b].trk); }));
    window.DECK_CLEANUP.push(stopSnd);
    runLoop(t => {
      tNow = t;
      let F = futureState(t, man); if (!F) { man = null; F = futureState(t); }
      svg.innerHTML = futureSVG(F);
      f1.classList.toggle('on', F.phase === 'neglect'); f2.classList.toggle('on', F.phase === 'restore');
      sl.querySelectorAll('.dypol .dyarcade').forEach(b => b.classList.toggle('down', b.dataset.p === F.pol && F.ph < 1));
    }, 48);
  },
});

/* =====================================================================
   dycaravan: القافلة على السكة — IR يراها ⇐ 'S' قف ⇐ الراوي ⇐ 'G' تحرك
   ===================================================================== */
function camel(x, y, k = 1, ph = 0) {
  const l = Math.sin(ph) * 6;
  return `<g transform="translate(${x} ${y}) scale(${k})">
    <line x1="-18" y1="-14" x2="${-20 + l}" y2="18" stroke="#8a5a2c" stroke-width="5"/><line x1="-8" y1="-14" x2="${-8 - l}" y2="18" stroke="#8a5a2c" stroke-width="5"/>
    <line x1="14" y1="-14" x2="${14 + l}" y2="18" stroke="#8a5a2c" stroke-width="5"/><line x1="24" y1="-14" x2="${24 - l}" y2="18" stroke="#8a5a2c" stroke-width="5"/>
    <ellipse cx="3" cy="-22" rx="30" ry="13" fill="#c08a4e"/><path d="M-12 -30 q8 -22 18 0z" fill="#c08a4e"/>
    <path d="M-26 -24 q-14 -8 -14 -30" stroke="#c08a4e" stroke-width="9" fill="none" stroke-linecap="round"/>
    <ellipse cx="-44" cy="-55" rx="10" ry="6" fill="#c08a4e"/>
    <rect x="-6" y="-46" width="22" height="12" rx="3" fill="#b5462e"/><rect x="-6" y="-46" width="22" height="12" rx="3" fill="none" stroke="#f0cc7a" stroke-width="2"/></g>`;
}
// المسار: البداية عند اليمين (x=930) ثم المحطات ١ و٢ و٣ ثم نهاية السكة، ثم العودة
const CV = { home: 930, st: [720, 470, 220], end: 90, v: 70, hold: 6, back: 220 };
function caravanPlan() {
  const seg = []; let t = 0, x = CV.home;
  seg.push({ a: t, b: t + 1.2, x0: x, x1: x, k: 'start' }); t += 1.2;
  CV.st.forEach((sx, i) => {
    const d = (x - sx) / CV.v; seg.push({ a: t, b: t + d, x0: x, x1: sx, k: 'move', next: i }); t += d; x = sx;
    seg.push({ a: t, b: t + CV.hold, x0: x, x1: x, k: 'hold', st: i }); t += CV.hold;
  });
  let d = (x - CV.end) / CV.v; seg.push({ a: t, b: t + d, x0: x, x1: CV.end, k: 'toend' }); t += d; x = CV.end;
  seg.push({ a: t, b: t + 2.5, x0: x, x1: x, k: 'decide' }); t += 2.5;
  d = (CV.home - x) / CV.back; seg.push({ a: t, b: t + d, x0: x, x1: CV.home, k: 'home' }); t += d;
  seg.push({ a: t, b: t + 1, x0: CV.home, x1: CV.home, k: 'idle' }); t += 1;
  return { seg, P: t };
}
const CPLAN = caravanPlan();
function caravanState(t) {
  const ph = t % CPLAN.P, s = CPLAN.seg.find(g => ph >= g.a && ph < g.b) || CPLAN.seg[CPLAN.seg.length - 1];
  const k = (ph - s.a) / (s.b - s.a), x = lerp(s.x0, s.x1, k);
  return { ph, s, k, x, since: ph - s.a };
}
const CMSG = {
  start: ['🚀', "The motion board sends 'T': the caravan tour begins"],
  move: ['🐪', 'The caravan moves along the rail… the sensors watch'],
  toend: ['🐪', 'Stations done… the caravan rolls to the end of the rail'],
  decide: ['🗳️', 'Decision time: the visitor chooses how to protect Diriyah'],
  home: ['↩️', 'Returning home until the limit switch'],
  idle: ['🟡', "At home… the yellow button sends 'R' for a new tour"],
};
function chip(x, y, w, lbl, on) {
  return `<g transform="translate(${x} ${y})"><rect width="${w}" height="62" rx="10" fill="#14324f" stroke="${on ? '#7ee2a8' : '#3a5a7a'}" stroke-width="${on ? 4 : 2}"/>
    <text x="${w / 2}" y="24" style="font:700 14px monospace;direction:ltr;text-anchor:middle;fill:#9aa8b8">ESP32</text>
    <text x="${w / 2}" y="50" class="dyt" style="font-size:18px;fill:#f0cc7a">${lbl}</text></g>`;
}
function caravanSVG(t) {
  const S = caravanState(t), g = S.s, xs = CV.st, hue = t * 1000 / HUE_MS;
  const holdSt = g.k === 'hold' ? g.st : -1, hitSt = holdSt >= 0 && S.since < 1.2 ? holdSt : -1;
  const pk = (from, to, ch, k) => { const x = lerp(from, to, k), y = 40 - Math.sin(k * Math.PI) * 26;
    return `<g transform="translate(${x} ${y})"><rect x="-22" y="-16" width="44" height="32" rx="6" fill="#7ee2a8"/><text y="9" style="font:800 22px monospace;direction:ltr;text-anchor:middle;fill:#06301b">'${ch}'</text></g>`; };
  let packet = '';
  if (g.k === 'hold' && S.since < .8) packet = pk(150, 850, 'S', S.since / .8);
  const prev = CPLAN.seg[CPLAN.seg.indexOf(g) - 1];
  if (g.k === 'move' && g.next > 0 && S.since < .8 || g.k === 'toend' && S.since < .8) packet = pk(150, 850, 'G', S.since / .8);
  if (g.k === 'start') packet = pk(850, 150, 'T', S.k);
  return `${DEFS}<rect width="1000" height="560" fill="url(#dySky)"/>${stars(26, 1000, 60)}
    ${chip(60, 10, 180, 'Board 1 · Sensors', holdSt >= 0)}${chip(760, 10, 180, 'Board 3 · Motion', g.k !== 'hold' && g.k !== 'decide' && g.k !== 'idle')}
    <path d="M150 40 Q 500 -10 850 40" stroke="#7ee2a8" stroke-width="2" stroke-dasharray="8 8" fill="none" opacity=".5"/>${packet}
    <rect x="30" y="96" width="940" height="270" rx="12" fill="#0a0c14" stroke="#2a2416" stroke-width="6"/>
    ${ST.map((s, i) => { const x = xs[i], on = holdSt === i, c = css(hueRGB(hue + i * 40));
      const art = i === 0 ? palace(x, 350, .58) : `<g transform="translate(${x} 350) scale(.56) translate(${-x} -350)">${i === 1 ? mosque(x, 350) : wadi(x, 350)}</g>`;
      return `${on ? `<path d="M${x - 12} 108 L${x - 110} 360 L${x + 110} 360 L${x + 12} 108z" fill="url(#dyCone)"/>` : ''}${art}
        <rect x="${x - 118}" y="102" width="236" height="258" fill="#050713" opacity="${on ? 0 : .6}"/>
        ${on ? `<circle cx="${x}" cy="352" r="10" fill="${c}"/><circle cx="${x}" cy="352" r="34" fill="${c}" opacity=".3"/>` : ''}
        ${irMod(x, 392, hitSt === i, .9)}${hitSt === i ? `<path d="M${x} 404 L${x - 28} 452 L${x + 28} 452z" fill="#ff4d4d" opacity=".3"/>` : ''}
        <text x="${x}" y="548" class="dyt" style="font-size:${s.n.length > 22 ? 13 : 20}px;fill:${on ? '#f0cc7a' : '#9aa0b8'}">${AR(i + 1)}. ${s.n}</text>
        ${on ? `<rect x="${x - 80}" y="508" width="${160 * (1 - S.since / CV.hold)}" height="6" rx="3" fill="#7ee2a8"/>` : ''}`; }).join('')}
    <rect x="40" y="470" width="920" height="16" rx="4" fill="#5a3a1c"/><rect x="40" y="466" width="920" height="4" fill="#8a611f"/>
    <line x1="60" y1="478" x2="940" y2="478" stroke="#222" stroke-width="5" stroke-dasharray="6 4" stroke-dashoffset="${-S.x}"/>
    <circle cx="955" cy="478" r="16" fill="#555" stroke="#999" stroke-width="3"/><circle cx="45" cy="478" r="12" fill="#555" stroke="#999" stroke-width="3"/>
    <rect x="958" y="440" width="38" height="44" rx="4" fill="#2b2b33" stroke="#9aa8b8" stroke-width="2"/><text x="977" y="500" style="font:700 12px monospace;direction:ltr;text-anchor:middle;fill:#9aa8b8">NEMA17</text>
    <rect x="${CV.home + 34}" y="452" width="12" height="16" fill="${g.k === 'idle' || g.k === 'start' ? '#ff4d4d' : '#666'}"/>
    <g transform="translate(${S.x} 468)"><rect x="-58" y="-6" width="116" height="10" rx="3" fill="#3a2a18"/>
      ${camel(-22, -24, .62, g.k === 'move' || g.k === 'toend' || g.k === 'home' ? t * 8 : 0)}${camel(26, -24, .62, g.k === 'move' || g.k === 'toend' || g.k === 'home' ? t * 8 + 1.5 : 0)}
      ${person(-52, -6, '#e8dcc0', g.k === 'move' ? t * 8 : 0, .34)}</g>`;
}
function caravanInfo(t) {
  const S = caravanState(t), g = S.s;
  if (g.k === 'hold') return S.since < .8 ? ['📡', `The “${ST[g.st].n}” sensor sees the caravan ⇒ board 1 sends 'S' ⇒ board 3 stops the motor`]
    : ['💡', `${ST[g.st].n}: spotlight, colors + narrator · 'G' in ${AR(Math.ceil((CV.hold - S.since) * 2))} s`];
  if (g.k === 'move' && g.next > 0 && S.since < .8) return ['📡', "Narration over ⇒ 'G' ⇒ the caravan moves to the next station"];
  return CMSG[g.k];
}
Object.assign(window.DECK_TYPES, {
  dycaravan: s => `<div class="slide light">
      <div class="kicker">🐪 The caravan on its historic road · NEMA17 + A4988 + GT2 belt</div>
      <h2 class="title" style="margin-bottom:12px">${s.title}</h2>
      <div class="dylab dycv">
        <div class="dygif ix"><svg viewBox="0 0 1000 560" class="dysvg" id="dycvs"></svg>${wrapCap('dycvc')}</div>
        <div class="dyside ix">
          <div class="dymsgs">${[['T', 'board 3 → board 1', 'Tour started'], ['S', 'board 1 → board 3', 'Stop here'], ['G', 'board 1 → board 3', 'Go'], ['R', 'board 2 → board 3', 'New tour']].map(m => `<div data-m="${m[0]}"><code>'${m[0]}'</code><span>${m[2]}</span><small>${m[1]}</small></div>`).join('')}</div>
          <div class="dyfacts"><div><span>Speed</span><b>~3 cm/s</b></div><div class="g"><span>Safety</span><b>Stops itself</b></div></div>
          <div class="dynote">If no sensor sees the caravan within about 80 cm, it stops by itself. After the tour, the show returns to “explore by hand” mode.</div>
        </div></div></div>`,
});
Object.assign(window.DECK_BIND, {
  dycaravan(sl) {
    const svg = sl.querySelector('#dycvs'), cap = sl.querySelector('#dycvc'), rows = sl.querySelectorAll('.dymsgs div');
    runLoop(t => {
      svg.innerHTML = caravanSVG(t); setCap(cap, caravanInfo(t));
      const S = caravanState(t), g = S.s;
      const m = g.k === 'start' ? 'T' : g.k === 'hold' && S.since < 1.2 ? 'S' : (g.k === 'move' && g.next > 0 || g.k === 'toend') && S.since < 1.2 ? 'G' : g.k === 'idle' ? 'R' : '';
      rows.forEach(r => r.classList.toggle('on', r.dataset.m === m));
    }, CPLAN.P);
  },
});
})();
