"""يولّد widgetsT_en.js وwidgetsT2_en.js وwidgetsT3_en.js (للعرض الإنجليزي masmak-judges-en)
من ملفات «لمسة تراث» العربية. شغّله بعد أي تعديل على widgetsT*.js:  python make-en.py
الترجمة تغطي الأدوات المستخدمة في عرض المحكّمين؛ وصوت الراوي من ../masmak-judges-en/audio"""
import re, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

COMMON = [
 ("const { AR, highlight, codeBlock } = window.ARD;", "const { highlight, codeBlock } = window.ARD; const AR = n => String(n);"),
 (".replace('.', '٫')", ""),
]
T = [
 ("محطة الأمان", "Safety station"),
 ("🌙 ليل هادئ… المحطة تراقب، وروبوتان يحرسان", "🌙 A quiet night… the station watches, two robots guard"),
 ("🔥💨 لهب عند البرج وتسرّب غاز معًا!", "🔥💨 A flame at the tower and a gas leak at once!"),
 ("🧠 القائد: اللهب لي ← أذهب بنفسي · 📡 وأأمر الروبوت ٢: إلى الغاز", "🧠 Leader: the fire is mine → I go myself · 📡 robot 2: go to the gas"),
 ("🚙🚙 الروبوتان ينطلقان معًا", "🚙🚙 Both robots set off together"),
 ("💧 المضخة تطفئ النار… 🌀 والمروحة تبدد الغاز", "💧 The pump puts out the fire… 🌀 the fan clears the gas"),
 ("✅ المصمك آمن… ويعود كلٌّ إلى مكانه بالاتجاه نفسه", "✅ Masmak is safe… each robot backs up to its place"),
 ("🛡️ لمسة تراث: تقنية تحمي التاريخ", "🛡️ Touch of Heritage: technology protecting history"),
]
T2 = [
 ("// إذن للثاني: إلى الغاز", "// permission: robot 2 to the gas"),
 ("// القائد بنفسه: إلى اللهب", "// the leader itself: to the fire"),
 ("// إذن للثاني: الغاز له", "// permission: the gas is robot 2's"),
 ("// اللهب للقائد نفسه", "// the fire is the leader's"),
 ("// للأمام حتى الشريط الأسود", "// forward to the black strip"),
 ("// المضخة", "// the pump"),
 ("// للخلف بالزمن نفسه: يعود مكانه", "// back for the same time: home"),
 (">تقاطع<", ">Junction<"), (">المنطقة A<", ">Zone A<"), (">البرج الغربي<", ">West tower<"), (">المنطقة B<", ">Zone B<"), (">مخزن الحطب<", ">Wood store<"),
 (">🏠 الانطلاق<", ">🏠 Start<"), (">محطة الأمان<", ">Safety station<"),
 (">🧠 القرار<", ">🧠 The decision<"),
 ("'🔥 نسبة خطر الحريق'", "'🔥 Fire danger level'"), ("'💨 نسبة خطر الغاز'", "'💨 Gas danger level'"),
 ("<span>الحد ${th}٪</span>", "<span>Threshold ${th}%</span>"),
 ("<b id=\"dl${z}v\">٠</b>%", "<b id=\"dl${z}v\">0</b>%"),
 ("<span>جرّب</span><button class=\"lsb\" data-p=\"85,0\">حريق فقط</button><button class=\"lsb\" data-p=\"0,70\">غاز فقط</button><button class=\"lsb\" data-p=\"80,70\">الاثنان معًا</button>",
  "<span>Try</span><button class=\"lsb\" data-p=\"85,0\">Fire only</button><button class=\"lsb\" data-p=\"0,70\">Gas only</button><button class=\"lsb\" data-p=\"80,70\">Both</button>"),
 ("🔴 القائد · 🔵 الروبوت ٢", "🔴 Leader · 🔵 Robot 2"),
 (">🚒 المهمة الكاملة<", ">🚒 The full mission<"),
 (">🔥 لهب A<", ">🔥 Fire A<"), (">💨 غاز B<", ">💨 Gas B<"), (">💨 غاز A<", ">💨 Gas A<"), (">🔥 لهب B<", ">🔥 Fire B<"),
 (">🔥💨 معًا: القائد والثاني<", ">🔥💨 Both: leader & robot 2<"),
 ("<span>زمن الاستجابة</span>", "<span>Response time</span>"), ("<span>مهمات منجزة</span>", "<span>Missions done</span>"), ("<b id=\"msn\">٠</b>", "<b id=\"msn\">0</b>"),
 ("'🔥 نعم' : 'لا'", "'🔥 yes' : 'no'"), ("'💨 نعم' : 'لا'", "'💨 yes' : 'no'"),
 ("'🔴 القائد يذهب بنفسه إلى اللهب · 📡 ويأمر 🔵 الروبوت ٢: إلى الغاز · ثم يعود كلٌّ مكانه'", "'🔴 The leader goes to the fire itself · 📡 and orders 🔵 robot 2 to the gas · then both return'"),
 ("'🔴 لهب وحده: القائد يذهب إليه ثم يعود بالاتجاه نفسه، و🔵 الروبوت ٢ يحرس'", "'🔴 Fire only: the leader goes, then backs up the same way; 🔵 robot 2 keeps guard'"),
 ("'💨 غاز وحده: القائد يبقى ويعطي 🔵 الروبوت ٢ الإذن: اذهب وتعامل معه'", "'💨 Gas only: the leader stays and gives 🔵 robot 2 permission: go and handle it'"),
 ("'🛡️ لا خطر: الروبوتان في مكانهما يحرسان'", "'🛡️ No danger: both robots stay on guard'"),
 ("+ ' ث'", "+ ' s'"), ("} ث</b>", "} s</b>"),
 ("const NAME = { 1: '🔴 الروبوت ١', 2: '🔵 الروبوت ٢' };", "const NAME = { 1: '🔴 Leader', 2: '🔵 Robot 2' };"),
 ("`${NAME[r]} وصل: ${type === 1 ? '💧 المضخة تعمل' : '🌀 المروحة تعمل'}`", "`${NAME[r]} arrived: ${type === 1 ? '💧 pump on' : '🌀 fan on'}`"),
 ("`✅ المنطقة ${z} آمنة (${NAME[r]})`", "`✅ Zone ${z} is safe (${NAME[r]})`"),
 ("`↩️ ${NAME[r]} يعود بالاتجاه نفسه للخلف`", "`↩️ ${NAME[r]} backs up the same way`"),
 ("'🏠 كلٌّ عاد إلى مكانه'", "'🏠 Both are back home'"),
 ("`📡 المحطة ترسل: ${fire ? '🔥 لهب في ' + fire : ''}${fire && gas ? ' · ' : ''}${gas ? '💨 غاز في ' + gas : ''}`", "`📡 Station sends: ${fire ? '🔥 fire in ' + fire : ''}${fire && gas ? ' · ' : ''}${gas ? '💨 gas in ' + gas : ''}`"),
 ("fire ? `🧠 ${NAME[1]}: اللهب لي… 📡 وأعطي ${NAME[2]} الأمر: إلى الغاز` : `🧠 ${NAME[1]}: غاز فقط ← 📡 أعطي ${NAME[2]} الإذن: اذهب وتعامل معه`", "fire ? `🧠 ${NAME[1]}: the fire is mine… 📡 ordering ${NAME[2]}: to the gas` : `🧠 ${NAME[1]}: gas only → 📡 giving ${NAME[2]} permission: go handle it`"),
 ("`🔵 ${NAME[2]} تلقّى الإذن ← إلى ${gas}`", "`🔵 ${NAME[2]} got permission → to ${gas}`"),
 ("`🧠 ${NAME[1]}: لهب ← أذهب بنفسي، و${NAME[2]} يحرس`", "`🧠 ${NAME[1]}: fire → I go myself, ${NAME[2]} keeps guard`"),
 ("'🔥💨 حدثان معًا: غاز في A ولهب في B'", "'🔥💨 Two events at once: gas in A and fire in B'"),
 ("`🚨 المحطة: ${e === 'both' ? 'الأحمر والأزرق يضيئان' : e[0] === '1' ? 'الليد الأحمر والبازر' : 'الليد الأزرق والبازر'}`", "`🚨 Station: ${e === 'both' ? 'red and blue LEDs on' : e[0] === '1' ? 'red LED and buzzer' : 'blue LED and buzzer'}`"),
 (" ث</b> ${t}</div>", " s</b> ${t}</div>"),
]
T3 = [
 ("const MSND = n => `../masmak-judges/audio/${n}.mp3`;", "const MSND = n => `../masmak-judges-en/audio/${n}.mp3`;"),
 ("{ n: 'الأبراج', en: 'The Towers', c: '#f0b429', ar: 'أبراج المصمك الأربعة… حراس من الطين واللبن',", "{ n: 'Towers', en: 'The Towers', c: '#f0b429', ar: 'Four mud-brick towers guarding the fortress',"),
 ("{ n: 'الفناء', en: 'The Courtyard', c: '#2ecc71', ar: 'الفناء الواسع… قلب القصر وملتقى أهله',", "{ n: 'Courtyard', en: 'The Courtyard', c: '#2ecc71', ar: 'The open courtyard, the heart of the fortress',"),
 ("{ n: 'المسجد', en: 'The Mosque', c: '#3498db', ar: 'المسجد… بأعمدته وسقفه من خشب الأثل',", "{ n: 'Mosque', en: 'The Mosque', c: '#3498db', ar: 'The mosque, with pillars and a tamarisk-wood roof',"),
 ("{ n: 'الديوانية', en: 'The Majlis', c: '#a55eea', ar: 'الديوانية… حيث يجتمع الناس ويُستقبل الضيوف',", "{ n: 'Majlis', en: 'The Majlis', c: '#a55eea', ar: 'The majlis, where guests were received',"),
 ("{ n: 'البوابة', en: 'The Gate', c: '#e67e22', ar: 'البوابة الخشبية… وفيها رأس الرمح الشهير منذ ١٩٠٢م',", "{ n: 'Gate', en: 'The Gate', c: '#e67e22', ar: 'The wooden gate, with the famous spearhead from 1902',"),
 ("int wait = 1500;              // أبطأ = أكبر", "int wait = 1500;              // bigger = slower"),
 ("// فعّل المحرك", "// enable the motor"), ("// الاتجاه", "// direction"),
 ("// الأبراج", "// towers"), ("// الفناء", "// courtyard"), ("// المسجد", "// mosque"), ("// الديوانية", "// majlis"),
 ("cmd = 's';   // الحارس", "cmd = 's';   // watchdog"),
 ("# 'r' أو 'l' أو 's'", "# 'r' or 'l' or 's'"), ("# حارس الرمشة", "# blink guard"), ("# البوابة بلا حركة", "# the gate, no rotation"),
 ("'كاميرا تتبع العين'", "'Eye-tracking camera'"),
 ("'كاميرا عادية أمام الزائر. لا أجهزة استشعار باهظة: الرؤية الحاسوبية تكفي. (الخطوة القادمة: نقلها إلى آيباد محمول)'", "'An ordinary camera in front of the visitor. No expensive sensors: computer vision is enough. (Next step: move it to a handheld iPad)'"),
 ("'برنامج تتبع البؤبؤ'", "'Pupil tracking'"),
 ("'بايثون + MediaPipe Face Landmarker: ٤٧٨ نقطة على الوجه، ويحدد موضع البؤبؤ داخل العين بعد معايرة ٢٫٥ ثانية.'", "'Python + MediaPipe Face Landmarker: 478 face points, locating the pupil inside the eye after a 2.5-second calibration.'"),
 ("'راسبيري باي: العقل المركزي'", "'Raspberry Pi: the central brain'"),
 ("'يشغّل الفيديو بلغة الإشارة والشرح الصوتي لكل جهة (VLC وmpg123)، ويعيد توجيه أوامر العين فورًا إلى ESP32 عبر UDP.'", "'Plays the sign-language video and the audio narration for each face (VLC and mpg123), and forwards eye commands instantly to the ESP32 over UDP.'"),
 ("'الشاشة والسماعة'", "'Screen and speaker'"),
 ("'فيديو بلغة الإشارة راجعه معلم لغة إشارة من مدرسة للصم، وشرح صوتي للمكفوفين، معًا في الوقت نفسه.'", "'A sign-language video reviewed by a sign-language teacher from a school for the deaf, plus audio narration for the blind, at the same time.'"),
 ("'ESP32 وحدة الحركة'", "'ESP32 motion unit'"),
 ("'يستقبل حرفًا واحدًا عبر UDP: r يمين، l يسار، s توقف. ومعه حارس يوقف المنصة إن انقطعت الرسائل أكثر من ثانية.'", "'Receives one letter over UDP: r right, l left, s stop. A watchdog stops the turntable if messages stop for more than a second.'"),
 ("'درايفر يحوّل نبضات STEP (26) وDIR (25) وEN (27، يعمل على LOW) إلى خطوات دقيقة. ومصدر 12 فولت مستقل للمحرك.'", "'A driver turning STEP (26), DIR (25) and EN (27, active LOW) pulses into precise steps, with a separate 12 V supply for the motor.'"),
 ("'شريط WS2812B'", "'WS2812B strip'"),
 ("'على GPIO23: لون مختلف لكل جهة، وموجة ضوئية أثناء الدوران، بسطوع مضبوط لتفادي التيار الزائد.'", "'On GPIO23: a different color for each face, a light wave while turning, with limited brightness to avoid excess current.'"),
 ("'الكرسي المتحرك LEGO'", "'LEGO wheelchair'"),
 ("'من LEGO SPIKE Prime لذوي الإعاقة الحركية الشديدة: «وضع القيادة» يقرّب الزائر، ثم «وضع الاستكشاف» يتحكم بالمجسم.'", "'Built with LEGO SPIKE Prime for severe motor disabilities: “drive mode” brings the visitor closer, then “explore mode” controls the model.'"),
 ("'روبوتا السلامة'", "'Safety robots'"),
 ("'محطة غاز ولهب على ESP32 تكلّم روبوتين عبر ESP-NOW: القائد يذهب إلى اللهب بنفسه ويعود، ويأمر الثاني بالذهاب إلى الغاز. حماية للزوار حين يزدحم المعرض.'", "'A gas and flame station on an ESP32 talks to two robots over ESP-NOW: the leader goes to the fire itself and returns, and orders the second robot to the gas. Protection for visitors in a crowded exhibition.'"),
 ("'١. الكاميرا ترى وجه الزائر'", "'1. The camera sees the visitor’s face'"),
 ("'٢. البؤبؤ مال يمينًا ← الأمر r'", "'2. The pupil moves right → command r'"),
 ("'٣. الراسبيري يعيد توجيه الأمر فورًا'", "'3. The Raspberry Pi forwards the command instantly'"),
 ("'٤. ESP32 يستقبل r عبر UDP'", "'4. The ESP32 receives r over UDP'"),
 ("'٥. A4988 ينبض والمجسم يدور يمينًا'", "'5. The A4988 pulses and the model turns right'"),
 ("'٦. موجة ضوئية أثناء الدوران'", "'6. A light wave while turning'"),
 ("'٧. الزائر ثبّت نظره للأمام ← s: توقف'", "'7. The visitor looks ahead → s: stop'"),
 ("'٨. فيديو لغة الإشارة والصوت لهذه الجهة'", "'8. Sign-language video and audio for this face'"),
 ("'🔇 الصوت مغلق'", "'🔇 Sound off'"), ("'🔊 الصوت يعمل'", "'🔊 Sound on'"), (">🔇 الصوت مغلق<", ">🔇 Sound off<"),
 ("'🎙️ الترحيب'", "'🎙️ Welcome'"),
 (">📷 تتبع العين<", ">📷 Eye tracking<"), (">📺 لغة الإشارة + الشرح الصوتي<", ">📺 Sign language + narration<"), (">🛡️ روبوت السلامة<", ">🛡️ Safety robot<"),
 (">🗺️ المنظومة كاملة<", ">🗺️ The whole system<"), (">العين والعقل والمحتوى<", ">Eye, brain and content<"), (">وحدة الحركة والإضاءة<", ">Motion and lighting unit<"),
 (">▶ شاهد نظرة واحدة<", ">▶ Watch one glance<"), (">👆 انقر أي جزء لتتعرف عليه<", ">👆 Click any part to learn about it<"),
 (">تسعة أجزاء… وتجربة واحدة يقودها الزائر بعينيه.<", ">Nine parts… one experience led by the visitor’s eyes.<"),
 (">⚙️ المنصة الدوّارة · A4988 + NEMA17<", ">⚙️ The turntable · A4988 + NEMA17<"),
 (">◀ l يسار<", ">◀ l left<"), (">⏹ s توقف<", ">⏹ s stop<"), (">r يمين ▶<", ">r right ▶<"),
 ("⏱️ wait بين النبضات: <b id=\"ttwv\">١٥٠٠</b> ميكروثانية", "⏱️ wait between pulses: <b id=\"ttwv\">1500</b> µs"),
 ("<span>الخطوات الدقيقة</span>", "<span>Microstepping</span>"), (">كاملة ×١<", ">Full ×1<"),
 ("<span>خطوات الدورة</span><b id=\"ttspr\">٣٢٠٠</b>", "<span>Steps per turn</span><b id=\"ttspr\">3200</b>"),
 ("<span>الزاوية</span><b id=\"tta\">٠°</b>", "<span>Angle</span><b id=\"tta\">0°</b>"), ("<span>زمن الدورة</span>", "<span>Turn time</span>"),
 (">🌈 شريط WS2812B<", ">🌈 WS2812B strip<"), (">🌊 موجة الدوران<", ">🌊 Turning wave<"), (">🎉 مكافأة الاهتمام<", ">🎉 Interest reward<"),
 ("☀️ السطوع: <b id=\"lgbv\">٦٠</b> من ٢٥٥", "☀️ Brightness: <b id=\"lgbv\">60</b> of 255"),
 ("<span>عدد الليدات</span><b>٢٤</b>", "<span>LEDs</span><b>24</b>"), ("<span>التيار التقريبي</span>", "<span>Approx. current</span>"), ("<span>طرف البيانات</span>", "<span>Data pin</span>"),
 (">📺 الراسبيري باي والشاشة<", ">📺 Raspberry Pi and screen<"),
 ("❄️ آخر إطار مجمّد<", "❄️ Last frame frozen<"), ("⬛ الفيديو انتهى… والصوت مستمر!", "⬛ The video ended… the audio goes on!"),
 (">🔊 الصوت<", ">🔊 Audio<"), (">🎞️ الفيديو<", ">🎞️ Video<"), (">❌ بلا تمديد<", ">❌ No extension<"),
 (">🍓 Raspberry Pi · بايثون<", ">🍓 Raspberry Pi · Python<"), (">فيديو بلغة الإشارة + شرح صوتي لكل جهة<", ">Sign-language video + narration for each face<"),
 ("# تمديد الفيديو بتجميد آخر إطار", "# extend the video by freezing the last frame"), ("# التشغيل معًا: صورة + صوت", "# play together: picture + sound"),
 (">📶 UDP والحارس<", ">📶 UDP and the watchdog<"), (">الحارس<", ">Watchdog<"),
 (">👁️ انظر يمينًا (اضغط مطولًا)<", ">👁️ Look right (press and hold)<"),
 ("📉 فقد الرسائل: <b id=\"udlv\">٠٪</b>", "📉 Message loss: <b id=\"udlv\">0%</b>"),
 ("'🛡️ الحارس: يعمل'", "'🛡️ Watchdog: on'"), (">🛡️ الحارس: يعمل<", ">🛡️ Watchdog: on<"), ("'🚫 الحارس: متوقف'", "'🚫 Watchdog: off'"),
 (">✂️ اقطع الشبكة<", ">✂️ Cut the network<"), ("'✂️ اقطع الشبكة'", "'✂️ Cut the network'"), ("'🔌 أعد الشبكة'", "'🔌 Restore network'"),
 ("<span>رسائل أُرسلت</span><b id=\"udns\">٠</b>", "<span>Sent</span><b id=\"udns\">0</b>"), ("<span>ضاعت</span><b id=\"udnl\">٠</b>", "<span>Lost</span><b id=\"udnl\">0</b>"),
 ("<span>دوران زائد</span>", "<span>Over-rotation</span>"),
 (">👁️ تتبع بؤبؤ العين<", ">👁️ Pupil tracking<"), (">🎯 معايرة ٢٫٥ ث<", ">🎯 Calibrate 2.5 s<"), (">😑 رمشة<", ">😑 Blink<"), (">😌 إغماضة طويلة<", ">😌 Long close<"),
 ("'🔢 المؤشرات: الصحيحة'", "'🔢 Indices: correct'"), (">🔢 المؤشرات: الصحيحة<", ">🔢 Indices: correct<"), ("'🔢 المؤشرات: الموثقة (خطأ!)'", "'🔢 Indices: documented (wrong!)'"),
 (">٠٫٥٠<", ">0.50<"), ("<span>الأمر</span>", "<span>Command</span>"), ("<span>المحتوى</span>", "<span>Content</span>"),
 (">🦽 الجولة الكاملة<", ">🦽 The full tour<"), (">📺 الشاشة<", ">📺 Screen<"), (">▶ ابدأ الجولة<", ">▶ Start the tour<"),
 (">◀ انظر يسارًا<", ">◀ Look left<"), (">انظر يمينًا ▶<", ">Look right ▶<"), (">⬆ انظر لأعلى<", ">⬆ Look up<"),
 (">⭐ قياس الاهتمام (قيد التطوير)<", ">⭐ Interest measure (in development)<"),
 ("'👁️ الزائر ينظر يمينًا… المجسّم يدور'", "'👁️ The visitor looks right… the model turns'"), ("`⏸ نظر للأمام: ${FACES[face].n}`", "`⏸ Looking ahead: ${FACES[face].n}`"),
 ("'😵 نبضات سريعة جدًا بلا خطوات دقيقة: المحرك يفقد خطواته ويهتز. أبطئ أو فعّل الخطوات الدقيقة'", "'😵 Pulses too fast without microstepping: the motor loses steps and shakes. Slow down or enable microstepping'"),
 ("'EN = HIGH: المحرك مُعطّل ولا يسحب تيارًا، فلا يسخن وهو واقف'", "'EN = HIGH: the motor is disabled and draws no current, so it stays cool at rest'"),
 ("كل نبضة على STEP = خطوة. ", "Each STEP pulse = one step. "), (" نبضة في الثانية، والدورة الكاملة ", " pulses per second; a full turn takes "), (" ثانية: بطء مقصود لعين تتابع", " s: deliberately slow for the eye to follow"),
 ("'⚠️ تيار كبير! منفذ USB أو منظم اللوحة لا يتحمله: خفّض السطوع أو غذِّ الشريط من مصدر ٥ فولت مستقل'", "'⚠️ High current! USB or the board regulator cannot supply it: lower the brightness or power the strip from a separate 5 V supply'"),
 ("لون «", "Color “"), ("»: الزائر يعرف الجهة باللون قبل أن يسمع الشرح", "”: the visitor knows the face by its color before hearing the story"),
 ("'موجة ذهبية تجري حول المنصة أثناء الدوران'", "'A golden wave runs around the turntable while turning'"),
 ("'🎉 فكرة قيد التطوير: الزائر أطال النظر إلى جهة… فالنظام يقرر مكافأته بإضاءة احتفالية'", "'🎉 In development: the visitor looked at a face for a long time… so the system rewards them with celebration lights'"),
 ("'🌊 أثناء الدوران'", "'🌊 While turning'"), ("'✅ تمديد بآخر إطار'", "'✅ Extend with last frame'"), ("'❌ بلا تمديد'", "'❌ No extension'"),
 ("❄️ آخر إطار مجمّد ", "❄️ Last frame frozen "), (" ث حتى ينتهي الصوت: المترجم والصورة لا يختفيان", " s until the audio ends: the interpreter never disappears"),
 ("⚠️ الصوت أطول من الفيديو بـ ", "⚠️ The audio is longer than the video by "), (" ث: شاشة سوداء والزائر الأصم فقد المترجم!", " s: a black screen, and the deaf visitor lost the interpreter!"),
 ("'🤟 فيديو لغة الإشارة والشرح الصوتي يبدآن معًا: الأصم يرى، والكفيف يسمع'", "'🤟 The sign-language video and narration start together: the deaf see, the blind hear'"),
 ("`آخر رسالة قبل ${AR(Math.min(9.9, silent).toFixed(1))} ث` : 'لا حارس'", "`last message ${AR(Math.min(9.9, silent).toFixed(1))} s ago` : 'no watchdog'"),
 ("'😱 الزائر توقف عن النظر لكن رسالة s ضاعت… والمنصة ما زالت تدور!'", "'😱 The visitor stopped looking but the s message was lost… and the turntable keeps turning!'"),
 ("'🛡️ لا رسائل منذ أكثر من ثانية: الحارس أوقف المنصة بأمان'", "'🛡️ No messages for over a second: the watchdog stopped the turntable safely'"),
 ("'رسالة r كل ١٠٠ ملي ثانية ما دام الزائر ينظر يمينًا'", "'An r message every 100 ms while the visitor looks right'"),
 ("'اضغط مطولًا على «انظر يمينًا»، ثم ارفع إصبعك. ارفع الفقد، أو اقطع الشبكة، أو أوقف الحارس'", "'Press and hold “Look right”, then release. Raise the loss, cut the network, or turn off the watchdog'"),
 ("`🎯 انظر للأمام… ${AR(calT.toFixed(1))}`", "`🎯 Look ahead… ${AR(calT.toFixed(1))}`"),
 ("'😌 إغماضة طويلة مقصودة'", "'😌 Deliberate long close'"), ("'😑 رمشة: توقف أماني'", "'😑 Blink: safety stop'"),
 ("'👉 ينظر يمينًا'", "'👉 Looking right'"), ("'👈 ينظر يسارًا'", "'👈 Looking left'"), ("'⬆ ينظر لأعلى: البوابة'", "'⬆ Looking up: the gate'"), ("'👁️ ينظر للأمام'", "'👁️ Looking ahead'"),
 ("'▶ اضغط «ابدأ الجولة» لترى تجربة زائر كاملة'", "'▶ Press “Start the tour” to see a full visitor experience'"),
 ("'📷 الكاميرا رأت وجهًا: رسالة ترحيب بالعربية والإنجليزية'", "'📷 The camera saw a face: a welcome in Arabic and English'"),
 ("'🦽 «وضع القيادة»: الكرسي يقرّب الزائر من المجسّم'", "'🦽 “Drive mode”: the chair brings the visitor to the model'"),
 ("'📏 حساس المسافة: أقل من ٤٠ سم ← «وضع الاستكشاف» (خطوة قادمة)'", "'📏 Distance sensor: under 40 cm → “explore mode” (next step)'"),
 ("'👁️ الآن العين تقود المجسّم: انظر يمينًا أو يسارًا'", "'👁️ Now the eye drives the model: look right or left'"),
 ("'⬆ نظر لأعلى: محتوى البوابة دون أن تتحرك المنصة'", "'⬆ Looked up: the gate content plays without turning'"),
 ("`⏸ ثبّت نظره ← توقف · فيديو بلغة الإشارة وشرح «", "`⏸ Gaze held → stop · sign-language video and narration “"),
 ("`🏁 ملخص الجولة (قيد التطوير): أكثر ما شدّك «", "`🏁 Tour summary (in development): what caught you most: “"),
 ("'🌍 ختام العرض: سؤال وجواب بالإنجليزية من الفريق'", "'🌍 Finale: a question and answer in English from the team'"),
 ("'اضغط زر ابدأ الجولة'", "'Press Start the tour'"), ("'👋 الترحيب'", "'👋 Welcome'"), ("'🦽 وضع القيادة'", "'🦽 Drive mode'"), ("'👁️ وضع الاستكشاف'", "'👁️ Explore mode'"), ("'🏁 انتهت الجولة'", "'🏁 Tour finished'"),
 ("'🎉 مكافأة الاهتمام'", "'🎉 Interest reward'"),
 ("'شرح ' + FACES", "'Explain: ' + FACES"),
 ("'<div>▶ اضغط «ابدأ الجولة» لترى تجربة زائر كاملة</div>'", "'<div>▶ Press “Start the tour” to see a full visitor experience</div>'"),
 ("'أهلًا بك", "'Welcome"),
 ("+ ' ث'", "+ ' s'"), (" ث`", " s`"), (" / ${AR(a)} ث`", " / ${AR(a)} s`"),
 ("+ ' سم'", "+ ' cm'"),
]
DIG = str.maketrans('٠١٢٣٤٥٦٧٨٩٫٪', '0123456789.%')
def build(src, dst, pairs):
    s = open(src, encoding='utf8').read()
    miss = []
    for a, b in COMMON + pairs:
        if a not in s: miss.append(a)
        s = s.replace(a, b)
    s = s.translate(DIG)
    open(dst, 'w', encoding='utf8').write(s)
    print(dst, 'missing:', len(miss)); [print('   ', m[:100]) for m in miss]
build('widgetsT.js', 'widgetsT_en.js', T)
build('widgetsT2.js', 'widgetsT2_en.js', T2)
build('widgetsT3.js', 'widgetsT3_en.js', T3)
