/* =====================================================================
   "Touch of Heritage" — English judging deck (WRO 2026, Puerto Rico)
   Widgets: ../turath/widgetsT*_en.js (generated by ../turath/make-en.py)
   ===================================================================== */
(function (root) {
root.DECK = {
  lang: 'en',
  title: 'Touch of Heritage',
  subtitle: 'The fully interactive Masmak Fortress',
  tag: 'WRO 2026 · Future Innovators · Judging presentation',
  author: 'Talent & AI Unit · Al-Arqam Schools',
  sectionLabel: 'Section',
  parts: ['all'],
  modules: [],
};
if (typeof module !== 'undefined' && module.exports) module.exports = root.DECK;
})(typeof window !== 'undefined' ? window : globalThis);
